// Generated by NOMARK Intents resolver (target: typescript)
// Composition: archive_compaction v0.4.0
// Stream legacy fund-flow rows from Postgres, enrich each with retention metadata, delete archived rows from the source table, then notify on completion.
import { setTimeout as sleep } from "node:timers/promises";
/** Runtime context passed between verbs — values produced by prior verbs are stored here. */
export interface Ctx {
  input: any;
  values: Record<string, any>;
  receipts: Record<string, { id: string; timestamp: string; sink: string; reversible: boolean }>;
}
function newCtx(input: any): Ctx {
  return { input, values: {}, receipts: {} };
}
async function __retry<T>(fn: () => Promise<T>, max: number, delayMs: number, backoff: "linear"|"exponential", jitter: boolean): Promise<T> {
  let lastErr: unknown;
  for (let attempt = 0; attempt < max; attempt++) {
    try { return await fn(); } catch (e) { lastErr = e; }
    const base = backoff === "exponential" ? delayMs * Math.pow(2, attempt) : delayMs * (attempt + 1);
    const wait = jitter ? base * (0.5 + Math.random()) : base;
    await sleep(wait);
  }
  throw lastErr;
}
function __receipt(sink: string, reversible = true) {
  return { id: crypto.randomUUID(), timestamp: new Date().toISOString(), sink, reversible };
}
/** Minimal predicate evaluator — opaque string per spec §3.1. Resolver chose JS. */
function __predicate(expr: string, row: any): boolean {
  // eslint-disable-next-line no-new-func
  return Boolean(new Function("row", `return (${expr});`)(row));
}
function __project<T>(expr: string, input: T): any {
  // eslint-disable-next-line no-new-func
  return new Function("input", "row", `return (${expr});`)(input, input);
}
function __reduce(expr: string, input: any[], initial: any): any {
  const m = expr.match(/^group_by\(([^)]+)\)\.(sum|count|avg|min|max)\(([^)]*)\)$/);
  if (m) {
    const [, key, op, field] = m;
    const groups = new Map<any, any[]>();
    for (const row of input) {
      const k = __project(key, row);
      if (!groups.has(k)) groups.set(k, []);
      groups.get(k)!.push(row);
    }
    const out: Record<string, any> = {};
    for (const [k, rows] of groups) {
      if (op === "count") out[String(k)] = rows.length;
      else {
        const vals = rows.map(r => __project(field, r));
        if (op === "sum") out[String(k)] = vals.reduce((a, b) => a + b, 0);
        else if (op === "avg") out[String(k)] = vals.reduce((a, b) => a + b, 0) / vals.length;
        else if (op === "min") out[String(k)] = Math.min(...vals);
        else if (op === "max") out[String(k)] = Math.max(...vals);
      }
    }
    return out;
  }
  const m2 = expr.match(/^(sum|count|avg|min|max)\(([^)]*)\)$/);
  if (m2) {
    const [, op, field] = m2;
    if (op === "count") return input.length;
    const vals = input.map(r => __project(field, r));
    if (op === "sum") return vals.reduce((a, b) => a + b, 0);
    if (op === "avg") return vals.reduce((a, b) => a + b, 0) / vals.length;
    if (op === "min") return Math.min(...vals);
    if (op === "max") return Math.max(...vals);
  }
  // generic reducer: treat expr as JS lambda "acc, row => ..."
  // eslint-disable-next-line no-new-func
  const fn = new Function("acc", "row", `return (${expr});`) as (a: any, r: any) => any;
  return input.reduce(fn, initial);
}
async function stream_legacy(ctx: Ctx): Promise<any[]> {
  // STREAM: host should adapt this to async iteration over a real cursor.
  const { default: pg } = await import("pg");
  const client = new pg.Client({"__rawJs":"process.env.DATABASE_URL"});
  await client.connect();
  try {
    const r = await client.query(`SELECT * FROM fund_flow_legacy`);
    return r.rows;
  } finally { await client.end(); }
}

async function enrich_retention(ctx: Ctx): Promise<any> {
  const input = ctx.input;
  const extras = {"archived_at":"now()","retention_days":30};
  return Array.isArray(input) ? input.map(r => ({ ...r, ...extras })) : { ...input, ...extras };
}

async function purge_archived(ctx: Ctx): Promise<any> {
  const { default: pg } = await import("pg");
  const client = new pg.Client({"__rawJs":"process.env.DATABASE_URL"});
  await client.connect();
  try {
    await client.query(`DELETE FROM fund_flow_legacy WHERE archived_at < now() - interval(retention_days)`);
  } finally { await client.end(); }
  const receipt = __receipt("sql:fund_flow_legacy", false);
  ctx.receipts["purge_archived"] = receipt;
  return receipt;
}

async function notify_done(ctx: Ctx): Promise<any> {
  const payload = ctx.values["notify_done"] ?? ctx.input;
  await fetch("", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ channel: "#data-ops", text: typeof payload === "string" ? payload : JSON.stringify(payload) }) });
  // fire-and-forget per spec §3.6
  return;
}

async function __execute(id: string, ctx: Ctx): Promise<void> {
  switch (id) {
    case "stream_legacy": {
      ctx.values["stream_legacy"] = await stream_legacy(ctx);
      return __execute("enrich_retention", ctx);
    }
    case "enrich_retention": {
      ctx.values["enrich_retention"] = await enrich_retention(ctx);
      return __execute("purge_archived", ctx);
    }
    case "purge_archived": {
      ctx.values["purge_archived"] = await purge_archived(ctx);
      return __execute("notify_done", ctx);
    }
    case "notify_done": {
      ctx.values["notify_done"] = await notify_done(ctx);
      return;
    }
    default: throw new Error(`unknown verb id: ${id}`);
  }
}

export async function run(input: any): Promise<Ctx> {
  const ctx = newCtx(input);
  await __execute("stream_legacy", ctx);
  return ctx;
}
