import { BaseResolver, type VerbHandler } from '../core/resolver.js'
import { partitionVerbs, type Composition, type ComputeVerb, type SurfaceVerb, type Verb } from '../core/ir.js'

type MonitorParams = {
  subject?: string
  data?: unknown
  refresh?: { value?: number; unit?: string }
}
type ArrangeParams = { type?: string; density?: string; children?: readonly string[] }
type DisplayParams = { type?: string; data?: string; emphasis?: string; label?: string }
type StatusParams = { type?: string; message?: string }
type GuideParams = { type?: string; message?: string; priority?: string }

const PREAMBLE_HELPERS = `<script lang="ts" module>
  export type DashboardState = {
    values: Record<string, unknown>;
    status: 'idle' | 'loading' | 'empty';
    alerts: readonly string[];
  };
</script>

<script lang="ts">
  let { state }: { state: DashboardState } = $props();
</script>
`

/** Sort surface verbs leaf-first so each snippet is defined before any caller
 *  references it. Order: DISPLAY/STATUS/GUIDE (leaves, in composition order)
 *  → ARRANGE → MONITOR. Snippets in Svelte 5 hoist, but emit order matters
 *  for byte-equality and readability. */
function leafFirst(verbs: readonly Verb[]): Verb[] {
  const rank = (v: Verb): number => {
    if (v.verb === 'MONITOR') return 3
    if (v.verb === 'ARRANGE') return 2
    return 1
  }
  return [...verbs].sort((a, b) => {
    const ra = rank(a)
    const rb = rank(b)
    if (ra !== rb) return ra - rb
    return verbs.indexOf(a) - verbs.indexOf(b)
  })
}

export class SvelteBackend extends BaseResolver {
  readonly label = 'svelte'

  protected handlers: Partial<Record<ComputeVerb | SurfaceVerb, VerbHandler>> = {
    MONITOR: (v) => this.emitMonitor(v),
    ARRANGE: (v) => this.emitArrange(v),
    DISPLAY: (v) => this.emitDisplay(v),
    STATUS: (v) => this.emitStatus(v),
    GUIDE: (v) => this.emitGuide(v),
  }

  protected override handlerKind(): 'compute' | 'surface' {
    return 'surface'
  }

  protected override targetVerbs(c: Composition): { handled: Verb[]; stripped: Verb[] } {
    const { compute, surface } = partitionVerbs(c)
    return { handled: leafFirst(surface), stripped: compute }
  }

  protected rootFileName(_c: Composition): string {
    return 'Dashboard.svelte'
  }

  protected emitPreamble(c: Composition): string {
    const header = [
      '<!-- Generated by NOMARK Intents resolver (target: svelte) -->',
      `<!-- Composition: ${c.name} v${c.version} -->`,
      `<!-- ${c.description ?? ''} -->`,
    ].join('\n')
    return `${header}\n${PREAMBLE_HELPERS}`
  }

  protected emitPostamble(c: Composition): string {
    const { surface } = partitionVerbs(c)
    const monitor = surface.find((v) => v.verb === 'MONITOR')
    if (!monitor) throw new Error('Svelte backend requires a MONITOR verb')
    return `{@render ${monitor.id}(state)}\n`
  }

  private emitMonitor(v: Verb): string {
    const p = (v.params ?? {}) as MonitorParams
    const subject = p.subject ?? ''
    const refresh = p.refresh ? `${p.refresh.value}${p.refresh.unit}` : ''
    // The snippet body composes statuses + guides + the (single) ARRANGE.
    // Look up siblings via the composition the dispatcher already iterated.
    const siblings = this.lastComposition?.verbs ?? []
    const statuses = siblings.filter((s) => s.verb === 'STATUS')
    const guides = siblings.filter((g) => g.verb === 'GUIDE')
    const arrange = siblings.find((a) => a.verb === 'ARRANGE')
    if (!arrange) throw new Error('Svelte backend requires an ARRANGE verb')

    const renderLines = [
      ...statuses.map((s) => `    {@render ${s.id}(state)}`),
      ...guides.map((g) => `    {@render ${g.id}(state)}`),
      `    {@render ${arrange.id}(state)}`,
    ]

    return `{#snippet ${v.id}(state: DashboardState)}
  <main
    data-monitor='${v.id}'
    data-subject='${subject}'
    data-refresh='${refresh}'
  >
${renderLines.join('\n')}
  </main>
{/snippet}
`
  }

  private emitArrange(v: Verb): string {
    const p = (v.params ?? {}) as ArrangeParams
    const type = p.type ?? ''
    const density = p.density ?? ''
    const children = p.children ?? []
    const childrenAttr = children.join(',')
    const childRenders = children.map((c) => `    {@render ${c}(state)}`)
    return `{#snippet ${v.id}(state: DashboardState)}
  <div
    data-arrange='${type}'
    data-density='${density}'
    data-children='${childrenAttr}'
  >
${childRenders.join('\n')}
  </div>
{/snippet}
`
  }

  private emitDisplay(v: Verb): string {
    const p = (v.params ?? {}) as DisplayParams
    const type = p.type ?? ''
    const emphasis = p.emphasis ?? ''
    const dataKey = p.data ?? ''
    const openTag = `<section data-display='${v.id}' data-type='${type}' data-emphasis='${emphasis}'>`
    if (type === 'metric') {
      const label = p.label ?? ''
      return `{#snippet ${v.id}(state: DashboardState)}
  ${openTag}
    <header>${label}</header>
    <strong>{String(state.values['${dataKey}'] ?? '—')}</strong>
  </section>
{/snippet}
`
    }
    if (type === 'chart') {
      return `{#snippet ${v.id}(state: DashboardState)}
  ${openTag}
    <pre>{JSON.stringify(state.values['${dataKey}'] ?? null, null, 2)}</pre>
  </section>
{/snippet}
`
    }
    return `{#snippet ${v.id}(state: DashboardState)}
  ${openTag}
    <!-- unhandled DISPLAY.type='${type}' -->
  </section>
{/snippet}
`
  }

  private emitStatus(v: Verb): string {
    const p = (v.params ?? {}) as StatusParams
    const type = p.type ?? ''
    const message = p.message ?? ''
    return `{#snippet ${v.id}(state: DashboardState)}
  {#if state.status === '${type}'}
    <div role='status' aria-live='polite' data-status='${type}'>
      ${message}
    </div>
  {/if}
{/snippet}
`
  }

  private emitGuide(v: Verb): string {
    const p = (v.params ?? {}) as GuideParams
    const message = p.message ?? ''
    const priority = p.priority ?? ''
    return `{#snippet ${v.id}(state: DashboardState)}
  {#if state.alerts.includes('${v.id}')}
    <div role='alert' data-guide='${v.id}' data-priority='${priority}'>
      ${message}
    </div>
  {/if}
{/snippet}
`
  }

  private lastComposition: Composition | undefined

  override resolve(composition: Composition) {
    this.lastComposition = composition
    return super.resolve(composition)
  }
}
