// Generated by NOMARK Intents resolver (target: react)
// Composition: admin_console v0.4.0
// Interactive admin console: configure thresholds, decide on approvals, explore audit log, author rules, onboard new admins.
import { type ReactNode } from 'react';

export type DashboardState = {
  values: Record<string, unknown>;
  status: 'idle' | 'loading' | 'empty';
  alerts: readonly string[];
  selections: Record<string, unknown>;
  drafts: Record<string, unknown>;
};

export type DashboardDispatch = (event: { verb: string; id: string; action: string; payload: unknown }) => void;

function admin_view(children: ReactNode): ReactNode {
  return (
    <main
      data-monitor='admin_view'
      data-subject='admin operations'
      data-refresh='1s'
    >
      {children}
    </main>
  );
}

function tabs(children: ReactNode): ReactNode {
  return (
    <div
      data-arrange='tabs'
      data-density='comfortable'
      data-children='threshold_form,approval_choice,audit_search,rule_editor,admin_setup,admin_email'
    >
      {children}
    </div>
  );
}

function threshold_form(state: DashboardState, dispatch: DashboardDispatch): ReactNode {
  return (
    <form data-configure='threshold_form' data-prompt='System thresholds'>
      <label>
        Alert threshold (USD)
        <input
          name='threshold_usd'
          type='number'
          defaultValue={String(state.drafts['threshold_usd'] ?? state.values['threshold_usd'] ?? '')}
          onChange={(e) => dispatch({ verb: 'CONFIGURE', id: 'threshold_form', action: 'set', payload: { threshold_usd: e.currentTarget.value } })}
        />
      </label>
      <label>
        Alert channel
        <input
          name='alert_channel'
          type='text'
          defaultValue={String(state.drafts['alert_channel'] ?? state.values['alert_channel'] ?? '')}
          onChange={(e) => dispatch({ verb: 'CONFIGURE', id: 'threshold_form', action: 'set', payload: { alert_channel: e.currentTarget.value } })}
        />
      </label>
      <button type='button' onClick={() => dispatch({ verb: 'CONFIGURE', id: 'threshold_form', action: 'apply', payload: state.drafts })}>Apply</button>
    </form>
  );
}

function approval_choice(state: DashboardState, dispatch: DashboardDispatch): ReactNode {
  return (
    <form data-decide='approval_choice' data-prompt='Approve this transaction?'>
      <button
        type='button'
        data-option='approve'
        onClick={() => dispatch({ verb: 'DECIDE', id: 'approval_choice', action: 'select', payload: 'approve' })}
      >
        Approve
      </button>
      <button
        type='button'
        data-option='reject'
        onClick={() => dispatch({ verb: 'DECIDE', id: 'approval_choice', action: 'select', payload: 'reject' })}
      >
        Reject
      </button>
    </form>
  );
}

function audit_search(state: DashboardState, dispatch: DashboardDispatch): ReactNode {
  const results = (state.values['audit_log'] as readonly { id: string; label: string }[] | undefined) ?? [];
  return (
    <section data-explore='audit_search' data-prompt='Audit log' data-source='audit_log'>
      <input
        type='search'
        placeholder='Search events...'
        defaultValue={String(state.drafts['audit_search'] ?? '')}
        onChange={(e) => dispatch({ verb: 'EXPLORE', id: 'audit_search', action: 'query', payload: e.currentTarget.value })}
      />
      <ul role='listbox'>
        {results.map((r) => (
          <li key={r.id} data-result-id={r.id}>{r.label}</li>
        ))}
      </ul>
    </section>
  );
}

function rule_editor(state: DashboardState, dispatch: DashboardDispatch): ReactNode {
  return (
    <form data-author='rule_editor' data-prompt='Edit rule' data-schema='rules.v1' data-save-mode='manual'>
      <output data-schema-ref='rules.v1'>
        {String(state.drafts['rule_editor'] ?? state.values['rule_editor'] ?? '')}
      </output>
      <textarea
        name='rule_editor'
        defaultValue={String(state.drafts['rule_editor'] ?? state.values['rule_editor'] ?? '')}
        onChange={(e) => dispatch({ verb: 'AUTHOR', id: 'rule_editor', action: 'edit', payload: e.currentTarget.value })}
      />
      <button type='button' onClick={() => dispatch({ verb: 'AUTHOR', id: 'rule_editor', action: 'save', payload: state.drafts['rule_editor'] })}>Save</button>
    </form>
  );
}

function admin_setup(state: DashboardState, dispatch: DashboardDispatch): ReactNode {
  const current = String(state.selections['admin_setup'] ?? 'profile');
  return (
    <nav data-onboard='admin_setup' data-prompt='New admin setup' data-progress-type='step'>
      <ol>
        <li data-step='profile' data-active={String(current === 'profile')}>Profile</li>
        <li data-step='permissions' data-active={String(current === 'permissions')}>Permissions</li>
        <li data-step='review' data-active={String(current === 'review')}>Review</li>
      </ol>
      <button type='button' data-step-action='advance' onClick={() => dispatch({ verb: 'ONBOARD', id: 'admin_setup', action: 'advance', payload: current })}>Next</button>
      <button type='button' data-step-action='skip' onClick={() => dispatch({ verb: 'ONBOARD', id: 'admin_setup', action: 'skip', payload: current })}>Skip</button>
    </nav>
  );
}

function admin_email(state: DashboardState, dispatch: DashboardDispatch): ReactNode {
  return (
    <label data-collect='admin_email' data-collect-type='text'>
      Admin email
      <input
        type='text'
        name='email'
        required={true}
        defaultValue={String(state.drafts['email'] ?? '')}
        onChange={(e) => dispatch({ verb: 'COLLECT', id: 'admin_email', action: 'input', payload: e.currentTarget.value })}
      />
    </label>
  );
}

export function Dashboard(state: DashboardState, dispatch: DashboardDispatch): ReactNode {
  return admin_view(
    <>
      {tabs(
        <>
          {threshold_form(state, dispatch)}
          {approval_choice(state, dispatch)}
          {audit_search(state, dispatch)}
          {rule_editor(state, dispatch)}
          {admin_setup(state, dispatch)}
          {admin_email(state, dispatch)}
        </>,
      )}
    </>,
  );
}
