"""
Generated by NOMARK Intents resolver (target: python).
Composition: flow_routing v0.4.0
Conditional pipeline: validate, route on status, map+persist on success or terminate on failure.
"""
from __future__ import annotations
import asyncio
import dataclasses
import json
import os
import random
import re
import time
import uuid
from typing import Any, Callable, Dict, List, Optional
@dataclasses.dataclass
class Ctx:
    input: Any = None
    values: Dict[str, Any] = dataclasses.field(default_factory=dict)
    receipts: Dict[str, Dict[str, Any]] = dataclasses.field(default_factory=dict)
async def _retry(fn: Callable[[], Any], max_attempts: int, delay_ms: int,
                 backoff: str = "exponential", jitter: bool = False) -> Any:
    last_err: Optional[BaseException] = None
    for attempt in range(max_attempts):
        try:
            return await fn()
        except Exception as e:
            last_err = e
        base = delay_ms * (2 ** attempt) if backoff == "exponential" else delay_ms * (attempt + 1)
        wait = base * (0.5 + random.random()) if jitter else base
        await asyncio.sleep(wait / 1000.0)
    raise last_err  # type: ignore[misc]
def _receipt(sink: str, reversible: bool = True) -> Dict[str, Any]:
    return {
        "id": str(uuid.uuid4()),
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "sink": sink,
        "reversible": reversible,
    }
def _predicate(expr: str, row: Any) -> bool:
    """Opaque expression evaluator — spec §3.1. Resolver chose Python eval."""
    return bool(eval(expr, {"__builtins__": {}}, {"row": row, "r": row}))
def _project(expr: str, input: Any) -> Any:
    return eval(expr, {"__builtins__": {"len": len, "sum": sum, "min": min, "max": max}},
                {"input": input, "row": input, "r": input})
def _reduce(expr: str, items: List[Any], initial: Any) -> Any:
    m = re.match(r"^group_by\(([^)]+)\)\.(sum|count|avg|min|max)\(([^)]*)\)$", expr)
    if m:
        key_expr, op, field = m.group(1), m.group(2), m.group(3)
        groups: Dict[Any, List[Any]] = {}
        for row in items:
            k = _project(key_expr, row)
            groups.setdefault(k, []).append(row)
        out: Dict[str, Any] = {}
        for k, rows in groups.items():
            if op == "count":
                out[str(k)] = len(rows)
                continue
            vals = [_project(field, r) for r in rows]
            if op == "sum": out[str(k)] = sum(vals)
            elif op == "avg": out[str(k)] = sum(vals) / len(vals)
            elif op == "min": out[str(k)] = min(vals)
            elif op == "max": out[str(k)] = max(vals)
        return out
    m2 = re.match(r"^(sum|count|avg|min|max)\(([^)]*)\)$", expr)
    if m2:
        op, field = m2.group(1), m2.group(2)
        if op == "count": return len(items)
        vals = [_project(field, r) for r in items]
        if op == "sum": return sum(vals)
        if op == "avg": return sum(vals) / len(vals) if vals else 0
        if op == "min": return min(vals) if vals else None
        if op == "max": return max(vals) if vals else None
    # generic lambda fallback: expr must name 'acc' and 'row'
    acc = initial
    for row in items:
        acc = eval(expr, {"__builtins__": {}}, {"acc": acc, "row": row})
    return acc
async def fetch_data(ctx: Ctx) -> Any:
    import httpx
    async with httpx.AsyncClient() as client:
        r = await client.request("GET", "https://api.example.com/records", json=None)
        r.raise_for_status()
        return r.json()


async def validate(ctx: Ctx) -> Any:
    input = ctx.input
    rules = [{"field": "status", "check": "required"}]
    validator = globals().get("__validator__")
    ok = validator(rules, input) if validator else True
    if not ok:
        action = "reject"
        if action == "reject":
            raise ValueError("VALIDATE validate failed")
        if action == "route":
            await _execute("", ctx)
            return ctx.values.get("")
        if action == "flag":
            return {**(input if isinstance(input, dict) else {"value": input}), "__flagged": True}
    return input


async def route_by_status(ctx: Ctx) -> Any:
    if _predicate("status == \"ok\"", ctx.input):
        await _execute("map_record", ctx)
        return ctx.values.get("map_record")
    await _execute("abort", ctx)
    return ctx.values.get("abort")


async def map_record(ctx: Ctx) -> Any:
    input = ctx.input
    return _project("{ id: id, status: status, amount: amount }", input)


async def persist_data(ctx: Ctx) -> Any:
    input = ctx.input
    import asyncpg
    conn = await asyncpg.connect(os.environ.get("DATABASE_URL", ""))
    try:
        rows = input if isinstance(input, list) else [input]
        for row in rows:
            keys = list(row.keys())
            placeholders = ", ".join(f"$" + str(i+1) for i in range(len(keys)))
            cols = ", ".join(keys)
            sql = f'INSERT INTO records ({cols}) VALUES ({placeholders})'
            await conn.execute(sql, *[row[k] for k in keys])
    finally:
        await conn.close()
    receipt = _receipt("sql:records")
    ctx.receipts["persist_data"] = receipt
    return receipt


async def abort(ctx: Ctx) -> Any:
    cleanup = []
    for cid in cleanup:
        await _execute(cid, ctx)
    raise _TerminateError("validation rejected", "failed")

class _TerminateError(Exception):
    def __init__(self, reason: str, status: str):
        super().__init__(f"__TERMINATE: {reason}")
        self.reason = reason
        self.status = status

async def _execute(vid: str, ctx: Ctx) -> None:
    if vid == "fetch_data":
        ctx.values["fetch_data"] = await fetch_data(ctx)
        await _execute("validate", ctx)
        return
    if vid == "validate":
        ctx.values["validate"] = await validate(ctx)
        await _execute("route_by_status", ctx)
        return
    if vid == "route_by_status":
        ctx.values["route_by_status"] = await route_by_status(ctx)
        return
        return
    if vid == "map_record":
        ctx.values["map_record"] = await map_record(ctx)
        await _execute("persist_data", ctx)
        return
    if vid == "persist_data":
        ctx.values["persist_data"] = await persist_data(ctx)
        return
        return
    if vid == "abort":
        ctx.values["abort"] = await abort(ctx)
        return
        return
    raise ValueError(f"unknown verb id: {vid}")

async def run(input: Any = None) -> Ctx:
    ctx = Ctx(input=input)
    try:
        await _execute("fetch_data", ctx)
    except _TerminateError:
        pass
    return ctx


if __name__ == "__main__":
    asyncio.run(run())
