// Generated by NOMARK Intents resolver (target: typescript)
// Composition: daily_fund_flow_etl v0.4.0
// Pull daily fund flow rows from an HTTP source, validate, normalize, aggregate per fund, upsert into Postgres, then notify on completion.
import { setTimeout as sleep } from "node:timers/promises";
/** Runtime context passed between verbs — values produced by prior verbs are stored here. */
export interface Ctx {
  input: any;
  values: Record<string, any>;
  receipts: Record<string, { id: string; timestamp: string; sink: string; reversible: boolean }>;
}
function newCtx(input: any): Ctx {
  return { input, values: {}, receipts: {} };
}
async function __retry<T>(fn: () => Promise<T>, max: number, delayMs: number, backoff: "linear"|"exponential", jitter: boolean): Promise<T> {
  let lastErr: unknown;
  for (let attempt = 0; attempt < max; attempt++) {
    try { return await fn(); } catch (e) { lastErr = e; }
    const base = backoff === "exponential" ? delayMs * Math.pow(2, attempt) : delayMs * (attempt + 1);
    const wait = jitter ? base * (0.5 + Math.random()) : base;
    await sleep(wait);
  }
  throw lastErr;
}
function __receipt(sink: string, reversible = true) {
  return { id: crypto.randomUUID(), timestamp: new Date().toISOString(), sink, reversible };
}
/** Minimal predicate evaluator — opaque string per spec §3.1. Resolver chose JS. */
function __predicate(expr: string, row: any): boolean {
  // eslint-disable-next-line no-new-func
  return Boolean(new Function("row", `return (${expr});`)(row));
}
function __project<T>(expr: string, input: T): any {
  // eslint-disable-next-line no-new-func
  return new Function("input", "row", `return (${expr});`)(input, input);
}
function __reduce(expr: string, input: any[], initial: any): any {
  const m = expr.match(/^group_by\(([^)]+)\)\.(sum|count|avg|min|max)\(([^)]*)\)$/);
  if (m) {
    const [, key, op, field] = m;
    const groups = new Map<any, any[]>();
    for (const row of input) {
      const k = __project(key, row);
      if (!groups.has(k)) groups.set(k, []);
      groups.get(k)!.push(row);
    }
    const out: Record<string, any> = {};
    for (const [k, rows] of groups) {
      if (op === "count") out[String(k)] = rows.length;
      else {
        const vals = rows.map(r => __project(field, r));
        if (op === "sum") out[String(k)] = vals.reduce((a, b) => a + b, 0);
        else if (op === "avg") out[String(k)] = vals.reduce((a, b) => a + b, 0) / vals.length;
        else if (op === "min") out[String(k)] = Math.min(...vals);
        else if (op === "max") out[String(k)] = Math.max(...vals);
      }
    }
    return out;
  }
  const m2 = expr.match(/^(sum|count|avg|min|max)\(([^)]*)\)$/);
  if (m2) {
    const [, op, field] = m2;
    if (op === "count") return input.length;
    const vals = input.map(r => __project(field, r));
    if (op === "sum") return vals.reduce((a, b) => a + b, 0);
    if (op === "avg") return vals.reduce((a, b) => a + b, 0) / vals.length;
    if (op === "min") return Math.min(...vals);
    if (op === "max") return Math.max(...vals);
  }
  // generic reducer: treat expr as JS lambda "acc, row => ..."
  // eslint-disable-next-line no-new-func
  const fn = new Function("acc", "row", `return (${expr});`) as (a: any, r: any) => any;
  return input.reduce(fn, initial);
}
async function fetch_rows(ctx: Ctx): Promise<any> {
  const r = await fetch("https://api.example.com/fund-flows/daily", {}); return await r.json();
}

async function validate_rows(ctx: Ctx): Promise<any> {
  const input = ctx.input;
  const rules: any = [{"field":"fund_id","check":"required"},{"field":"flow_usd","check":"numeric"},{"field":"trade_date","check":"required"}];
  // Basic schema check — host may inject Ajv via globalThis.__validator.
  const v = (globalThis as any).__validator;
  const ok = v ? v(rules)(input) : true;
  if (!ok) {
    const action = "reject";
    if (action === "reject") throw new Error("VALIDATE validate_rows failed");
    if (action === "route") { await __execute("", ctx); return ctx.values[""]; }
    if (action === "flag") return { ...input, __flagged: true };
  }
  return input;
}

async function normalize_region(ctx: Ctx): Promise<any> {
  const input = ctx.input;
  return __project("{ fund_id: fund_id, trade_date: trade_date, flow_usd: flow_usd, region: region }", input);
}

async function drop_zero(ctx: Ctx): Promise<any[]> {
  const input: any[] = ctx.input ?? [];
  return input.filter(row => __predicate("flow_usd != 0", row));
}

async function aggregate_daily(ctx: Ctx): Promise<any> {
  const input: any[] = ctx.input ?? [];
  return __reduce("group_by(fund_id,trade_date).sum(flow_usd)", input, null);
}

async function upsert_daily(ctx: Ctx): Promise<any> {
  const input = ctx.input;
  const { default: pg } = await import("pg");
  const client = new pg.Client({"__rawJs":"process.env.DATABASE_URL"});
  await client.connect();
  try {
    const rows: any[] = Array.isArray(input) ? input : [input];
    for (const row of rows) {
      const keys = Object.keys(row); const vals = Object.values(row);
      const placeholders = keys.map((_, i) => "$" + (i+1)).join(", ");
      const sql = `INSERT INTO fund_flow_daily (${keys.join(",")}) VALUES (${placeholders})`;
      await client.query(sql, vals);
    }
  } finally { await client.end(); }
  const receipt = __receipt("sql:fund_flow_daily");
  ctx.receipts["upsert_daily"] = receipt;
  return receipt;
}

async function notify_done(ctx: Ctx): Promise<any> {
  const payload = ctx.values["notify_done"] ?? ctx.input;
  await fetch("", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ channel: "#data-ops", text: typeof payload === "string" ? payload : JSON.stringify(payload) }) });
  // fire-and-forget per spec §3.6
  return;
}

async function __execute(id: string, ctx: Ctx): Promise<void> {
  switch (id) {
    case "fetch_rows": {
      ctx.values["fetch_rows"] = await fetch_rows(ctx);
      return __execute("validate_rows", ctx);
    }
    case "validate_rows": {
      ctx.values["validate_rows"] = await validate_rows(ctx);
      return __execute("normalize_region", ctx);
    }
    case "normalize_region": {
      ctx.values["normalize_region"] = await normalize_region(ctx);
      return __execute("drop_zero", ctx);
    }
    case "drop_zero": {
      ctx.values["drop_zero"] = await drop_zero(ctx);
      return __execute("aggregate_daily", ctx);
    }
    case "aggregate_daily": {
      ctx.values["aggregate_daily"] = await aggregate_daily(ctx);
      return __execute("upsert_daily", ctx);
    }
    case "upsert_daily": {
      ctx.values["upsert_daily"] = await upsert_daily(ctx);
      return __execute("notify_done", ctx);
    }
    case "notify_done": {
      ctx.values["notify_done"] = await notify_done(ctx);
      return;
    }
    default: throw new Error(`unknown verb id: ${id}`);
  }
}

export async function run(input: any): Promise<Ctx> {
  const ctx = newCtx(input);
  await __execute("fetch_rows", ctx);
  return ctx;
}
