import { BaseResolver, type VerbHandler } from '../core/resolver.js'
import { partitionVerbs, type Composition, type ComputeVerb, type SurfaceVerb, type Verb } from '../core/ir.js'

type MonitorParams = {
  subject?: string
  data?: unknown
  refresh?: { value?: number; unit?: string }
}
type ArrangeParams = { type?: string; density?: string; children?: readonly string[] }
type DisplayParams = { type?: string; data?: string; emphasis?: string; label?: string }
type StatusParams = { type?: string; message?: string }
type GuideParams = { type?: string; message?: string; priority?: string }

const PREAMBLE_HELPERS = `<script setup lang="ts">
import { h, defineRender, type VNode } from 'vue';

export type DashboardState = {
  values: Record<string, unknown>;
  status: 'idle' | 'loading' | 'empty';
  alerts: readonly string[];
};

const props = defineProps<{ state: DashboardState }>();
`

export class VueBackend extends BaseResolver {
  readonly label = 'vue'

  protected handlers: Partial<Record<ComputeVerb | SurfaceVerb, VerbHandler>> = {
    MONITOR: (v) => this.emitMonitor(v),
    ARRANGE: (v) => this.emitArrange(v),
    DISPLAY: (v) => this.emitDisplay(v),
    STATUS: (v) => this.emitStatus(v),
    GUIDE: (v) => this.emitGuide(v),
  }

  protected override handlerKind(): 'compute' | 'surface' {
    return 'surface'
  }

  protected override targetVerbs(c: Composition): { handled: Verb[]; stripped: Verb[] } {
    const { compute, surface } = partitionVerbs(c)
    return { handled: surface, stripped: compute }
  }

  protected rootFileName(_c: Composition): string {
    return 'Dashboard.vue'
  }

  protected emitPreamble(c: Composition): string {
    const header = [
      '<!-- Generated by NOMARK Intents resolver (target: vue) -->',
      `<!-- Composition: ${c.name} v${c.version} -->`,
      `<!-- ${c.description ?? ''} -->`,
    ].join('\n')
    return `${header}\n${PREAMBLE_HELPERS}`
  }

  protected emitPostamble(c: Composition): string {
    const { surface } = partitionVerbs(c)
    const monitor = surface.find((v) => v.verb === 'MONITOR')
    const arrange = surface.find((v) => v.verb === 'ARRANGE')
    const statuses = surface.filter((v) => v.verb === 'STATUS')
    const guides = surface.filter((v) => v.verb === 'GUIDE')

    if (!monitor) throw new Error('Vue backend requires a MONITOR verb')
    if (!arrange) throw new Error('Vue backend requires an ARRANGE verb')

    const arrangeParams = (arrange.params ?? {}) as ArrangeParams
    const children = arrangeParams.children ?? []

    const statusLines = statuses.map((s) => `  ${s.id}(props.state),`)
    const guideLines = guides.map((g) => `  ${g.id}(props.state),`)
    const childLines = children.map((childId) => `    ${childId}(props.state),`)

    const lines: string[] = [
      `defineRender(() => ${monitor.id}([`,
      ...statusLines,
      ...guideLines,
      `  ${arrange.id}([`,
      ...childLines,
      '  ]),',
      ']));',
      '</script>',
    ]

    return lines.join('\n') + '\n'
  }

  private emitMonitor(v: Verb): string {
    const p = (v.params ?? {}) as MonitorParams
    const subject = p.subject ?? ''
    const refresh = p.refresh ? `${p.refresh.value}${p.refresh.unit}` : ''
    return `function ${v.id}(children: readonly (VNode | null)[]): VNode {
  return h('main', {
    'data-monitor': '${v.id}',
    'data-subject': '${subject}',
    'data-refresh': '${refresh}',
  }, children.filter((c): c is VNode => c !== null));
}
`
  }

  private emitArrange(v: Verb): string {
    const p = (v.params ?? {}) as ArrangeParams
    const type = p.type ?? ''
    const density = p.density ?? ''
    const childrenAttr = (p.children ?? []).join(',')
    return `function ${v.id}(children: readonly VNode[]): VNode {
  return h('div', {
    'data-arrange': '${type}',
    'data-density': '${density}',
    'data-children': '${childrenAttr}',
  }, children);
}
`
  }

  private emitDisplay(v: Verb): string {
    const p = (v.params ?? {}) as DisplayParams
    const type = p.type ?? ''
    const emphasis = p.emphasis ?? ''
    const dataKey = p.data ?? ''
    const propsObj = `{ 'data-display': '${v.id}', 'data-type': '${type}', 'data-emphasis': '${emphasis}' }`
    if (type === 'metric') {
      const label = p.label ?? ''
      return `function ${v.id}(state: DashboardState): VNode {
  return h('section', ${propsObj}, [
    h('header', null, '${label}'),
    h('strong', null, String(state.values['${dataKey}'] ?? '—')),
  ]);
}
`
    }
    if (type === 'chart') {
      return `function ${v.id}(state: DashboardState): VNode {
  return h('section', ${propsObj}, [
    h('pre', null, JSON.stringify(state.values['${dataKey}'] ?? null, null, 2)),
  ]);
}
`
    }
    return `function ${v.id}(state: DashboardState): VNode {
  return h('section', ${propsObj}, [
    /* unhandled DISPLAY.type='${type}' */
  ]);
}
`
  }

  private emitStatus(v: Verb): string {
    const p = (v.params ?? {}) as StatusParams
    const type = p.type ?? ''
    const message = p.message ?? ''
    return `function ${v.id}(state: DashboardState): VNode | null {
  if (state.status !== '${type}') return null;
  return h('div', { role: 'status', 'aria-live': 'polite', 'data-status': '${type}' }, '${message}');
}
`
  }

  private emitGuide(v: Verb): string {
    const p = (v.params ?? {}) as GuideParams
    const message = p.message ?? ''
    const priority = p.priority ?? ''
    return `function ${v.id}(state: DashboardState): VNode | null {
  if (!state.alerts.includes('${v.id}')) return null;
  return h('div', { role: 'alert', 'data-guide': '${v.id}', 'data-priority': '${priority}' }, '${message}');
}
`
  }
}
