-- Generated by NOMARK Intents resolver (target: sql/sqlite)
-- Composition: archive_compaction v0.4.0
-- Stream legacy fund-flow rows from Postgres, enrich each with retention metadata, delete archived rows from the source table, then notify on completion.
BEGIN;
-- STREAM stream_legacy: cursor/iteration handled by host.
SELECT * FROM "fund_flow_legacy";

-- ENRICH enrich_retention
CREATE OR REPLACE VIEW v_enrich_retention AS SELECT *, now() AS "archived_at", 30 AS "retention_days" FROM source;

-- DELETE purge_archived
DELETE FROM "fund_flow_legacy" WHERE archived_at < now() - interval(retention_days);

-- EMIT (notify_done) not expressible as SQL. Host runtime required.
COMMIT;