"""
Generated by NOMARK Intents resolver (target: python).
Composition: daily_fund_flow_etl v0.4.0
Pull daily fund flow rows from an HTTP source, validate, normalize, aggregate per fund, upsert into Postgres, then notify on completion.
"""
from __future__ import annotations
import asyncio
import dataclasses
import json
import os
import random
import re
import time
import uuid
from typing import Any, Callable, Dict, List, Optional
@dataclasses.dataclass
class Ctx:
    input: Any = None
    values: Dict[str, Any] = dataclasses.field(default_factory=dict)
    receipts: Dict[str, Dict[str, Any]] = dataclasses.field(default_factory=dict)
async def _retry(fn: Callable[[], Any], max_attempts: int, delay_ms: int,
                 backoff: str = "exponential", jitter: bool = False) -> Any:
    last_err: Optional[BaseException] = None
    for attempt in range(max_attempts):
        try:
            return await fn()
        except Exception as e:
            last_err = e
        base = delay_ms * (2 ** attempt) if backoff == "exponential" else delay_ms * (attempt + 1)
        wait = base * (0.5 + random.random()) if jitter else base
        await asyncio.sleep(wait / 1000.0)
    raise last_err  # type: ignore[misc]
def _receipt(sink: str, reversible: bool = True) -> Dict[str, Any]:
    return {
        "id": str(uuid.uuid4()),
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "sink": sink,
        "reversible": reversible,
    }
def _predicate(expr: str, row: Any) -> bool:
    """Opaque expression evaluator — spec §3.1. Resolver chose Python eval."""
    return bool(eval(expr, {"__builtins__": {}}, {"row": row, "r": row}))
def _project(expr: str, input: Any) -> Any:
    return eval(expr, {"__builtins__": {"len": len, "sum": sum, "min": min, "max": max}},
                {"input": input, "row": input, "r": input})
def _reduce(expr: str, items: List[Any], initial: Any) -> Any:
    m = re.match(r"^group_by\(([^)]+)\)\.(sum|count|avg|min|max)\(([^)]*)\)$", expr)
    if m:
        key_expr, op, field = m.group(1), m.group(2), m.group(3)
        groups: Dict[Any, List[Any]] = {}
        for row in items:
            k = _project(key_expr, row)
            groups.setdefault(k, []).append(row)
        out: Dict[str, Any] = {}
        for k, rows in groups.items():
            if op == "count":
                out[str(k)] = len(rows)
                continue
            vals = [_project(field, r) for r in rows]
            if op == "sum": out[str(k)] = sum(vals)
            elif op == "avg": out[str(k)] = sum(vals) / len(vals)
            elif op == "min": out[str(k)] = min(vals)
            elif op == "max": out[str(k)] = max(vals)
        return out
    m2 = re.match(r"^(sum|count|avg|min|max)\(([^)]*)\)$", expr)
    if m2:
        op, field = m2.group(1), m2.group(2)
        if op == "count": return len(items)
        vals = [_project(field, r) for r in items]
        if op == "sum": return sum(vals)
        if op == "avg": return sum(vals) / len(vals) if vals else 0
        if op == "min": return min(vals) if vals else None
        if op == "max": return max(vals) if vals else None
    # generic lambda fallback: expr must name 'acc' and 'row'
    acc = initial
    for row in items:
        acc = eval(expr, {"__builtins__": {}}, {"acc": acc, "row": row})
    return acc
async def fetch_rows(ctx: Ctx) -> Any:
    import httpx
    async with httpx.AsyncClient() as client:
        r = await client.request("GET", "https://api.example.com/fund-flows/daily", json=None)
        r.raise_for_status()
        return r.json()


async def validate_rows(ctx: Ctx) -> Any:
    input = ctx.input
    rules = [{"field": "fund_id", "check": "required"}, {"field": "flow_usd", "check": "numeric"}, {"field": "trade_date", "check": "required"}]
    validator = globals().get("__validator__")
    ok = validator(rules, input) if validator else True
    if not ok:
        action = "reject"
        if action == "reject":
            raise ValueError("VALIDATE validate_rows failed")
        if action == "route":
            await _execute("", ctx)
            return ctx.values.get("")
        if action == "flag":
            return {**(input if isinstance(input, dict) else {"value": input}), "__flagged": True}
    return input


async def normalize_region(ctx: Ctx) -> Any:
    input = ctx.input
    return _project("{ fund_id: fund_id, trade_date: trade_date, flow_usd: flow_usd, region: region }", input)


async def drop_zero(ctx: Ctx) -> List[Any]:
    input = ctx.input or []
    return [row for row in input if _predicate("flow_usd != 0", row)]


async def aggregate_daily(ctx: Ctx) -> Any:
    input = ctx.input or []
    return _reduce("group_by(fund_id,trade_date).sum(flow_usd)", input, None)


async def upsert_daily(ctx: Ctx) -> Any:
    input = ctx.input
    import asyncpg
    conn = await asyncpg.connect(os.environ.get("DATABASE_URL", ""))
    try:
        rows = input if isinstance(input, list) else [input]
        for row in rows:
            keys = list(row.keys())
            placeholders = ", ".join(f"$" + str(i+1) for i in range(len(keys)))
            cols = ", ".join(keys)
            sql = f'INSERT INTO fund_flow_daily ({cols}) VALUES ({placeholders})'
            await conn.execute(sql, *[row[k] for k in keys])
    finally:
        await conn.close()
    receipt = _receipt("sql:fund_flow_daily")
    ctx.receipts["upsert_daily"] = receipt
    return receipt


async def notify_done(ctx: Ctx) -> None:
    payload = ctx.values.get("notify_done", ctx.input)
    import httpx
    async with httpx.AsyncClient() as client:
        body = {"channel": "#data-ops", "text": payload if isinstance(payload, str) else json.dumps(payload)}
        await client.post("", json=body)

async def _execute(vid: str, ctx: Ctx) -> None:
    if vid == "fetch_rows":
        ctx.values["fetch_rows"] = await fetch_rows(ctx)
        await _execute("validate_rows", ctx)
        return
    if vid == "validate_rows":
        ctx.values["validate_rows"] = await validate_rows(ctx)
        await _execute("normalize_region", ctx)
        return
    if vid == "normalize_region":
        ctx.values["normalize_region"] = await normalize_region(ctx)
        await _execute("drop_zero", ctx)
        return
    if vid == "drop_zero":
        ctx.values["drop_zero"] = await drop_zero(ctx)
        await _execute("aggregate_daily", ctx)
        return
    if vid == "aggregate_daily":
        ctx.values["aggregate_daily"] = await aggregate_daily(ctx)
        await _execute("upsert_daily", ctx)
        return
    if vid == "upsert_daily":
        ctx.values["upsert_daily"] = await upsert_daily(ctx)
        await _execute("notify_done", ctx)
        return
    if vid == "notify_done":
        ctx.values["notify_done"] = await notify_done(ctx)
        return
        return
    raise ValueError(f"unknown verb id: {vid}")

async def run(input: Any = None) -> Ctx:
    ctx = Ctx(input=input)
    await _execute("fetch_rows", ctx)
    return ctx


if __name__ == "__main__":
    asyncio.run(run())
