-- Generated by NOMARK Intents resolver (target: sql/postgres)
-- Composition: flow_routing v0.4.0
-- Conditional pipeline: validate, route on status, map+persist on success or terminate on failure.
BEGIN;
-- FETCH fetch_data
SELECT * FROM "src";

-- VALIDATE validate: rules must be enforced by host or CHECK constraints at schema time.

-- BRANCH route_by_status: conditional path selection handled by host runtime.

-- MAP map_record
CREATE OR REPLACE VIEW v_map_record AS SELECT id AS "id", status AS "status", amount AS "amount" FROM source;

-- PERSIST persist_data (mode: insert)
INSERT INTO "records" ("*unknown_columns*") VALUES ($1);

-- TERMINATE abort: ROLLBACK and abort transaction.
ROLLBACK;
COMMIT;