// Generated by NOMARK Intents resolver (target: typescript)
// Composition: flow_parallel v0.4.0
// Parallel fan-out by region, merge results, await settlement, gate on human review, signal external.
import { setTimeout as sleep } from "node:timers/promises";
/** Runtime context passed between verbs — values produced by prior verbs are stored here. */
export interface Ctx {
  input: any;
  values: Record<string, any>;
  receipts: Record<string, { id: string; timestamp: string; sink: string; reversible: boolean }>;
}
function newCtx(input: any): Ctx {
  return { input, values: {}, receipts: {} };
}
async function __retry<T>(fn: () => Promise<T>, max: number, delayMs: number, backoff: "linear"|"exponential", jitter: boolean): Promise<T> {
  let lastErr: unknown;
  for (let attempt = 0; attempt < max; attempt++) {
    try { return await fn(); } catch (e) { lastErr = e; }
    const base = backoff === "exponential" ? delayMs * Math.pow(2, attempt) : delayMs * (attempt + 1);
    const wait = jitter ? base * (0.5 + Math.random()) : base;
    await sleep(wait);
  }
  throw lastErr;
}
function __receipt(sink: string, reversible = true) {
  return { id: crypto.randomUUID(), timestamp: new Date().toISOString(), sink, reversible };
}
/** Minimal predicate evaluator — opaque string per spec §3.1. Resolver chose JS. */
function __predicate(expr: string, row: any): boolean {
  // eslint-disable-next-line no-new-func
  return Boolean(new Function("row", `return (${expr});`)(row));
}
function __project<T>(expr: string, input: T): any {
  // eslint-disable-next-line no-new-func
  return new Function("input", "row", `return (${expr});`)(input, input);
}
function __reduce(expr: string, input: any[], initial: any): any {
  const m = expr.match(/^group_by\(([^)]+)\)\.(sum|count|avg|min|max)\(([^)]*)\)$/);
  if (m) {
    const [, key, op, field] = m;
    const groups = new Map<any, any[]>();
    for (const row of input) {
      const k = __project(key, row);
      if (!groups.has(k)) groups.set(k, []);
      groups.get(k)!.push(row);
    }
    const out: Record<string, any> = {};
    for (const [k, rows] of groups) {
      if (op === "count") out[String(k)] = rows.length;
      else {
        const vals = rows.map(r => __project(field, r));
        if (op === "sum") out[String(k)] = vals.reduce((a, b) => a + b, 0);
        else if (op === "avg") out[String(k)] = vals.reduce((a, b) => a + b, 0) / vals.length;
        else if (op === "min") out[String(k)] = Math.min(...vals);
        else if (op === "max") out[String(k)] = Math.max(...vals);
      }
    }
    return out;
  }
  const m2 = expr.match(/^(sum|count|avg|min|max)\(([^)]*)\)$/);
  if (m2) {
    const [, op, field] = m2;
    if (op === "count") return input.length;
    const vals = input.map(r => __project(field, r));
    if (op === "sum") return vals.reduce((a, b) => a + b, 0);
    if (op === "avg") return vals.reduce((a, b) => a + b, 0) / vals.length;
    if (op === "min") return Math.min(...vals);
    if (op === "max") return Math.max(...vals);
  }
  // generic reducer: treat expr as JS lambda "acc, row => ..."
  // eslint-disable-next-line no-new-func
  const fn = new Function("acc", "row", `return (${expr});`) as (a: any, r: any) => any;
  return input.reduce(fn, initial);
}
async function fetch_orders(ctx: Ctx): Promise<any> {
  const r = await fetch("https://api.example.com/orders", {}); return await r.json();
}

async function fan_out(ctx: Ctx): Promise<any[]> {
  const targets: string[] = ["process_north","process_south","process_east"];
  const strategy = "parallel";
  void strategy; // 'parallel' | 'broadcast' | 'partition' — host may inspect
  const results = await Promise.all(targets.map(async (t) => {
    const branchCtx: Ctx = { input: ctx.input, values: {}, receipts: {} };
    await __execute(t, branchCtx);
    return branchCtx.values[t];
  }));
  ctx.values["fan_out" + ":branches"] = results;
  return results;
}

async function process_north(ctx: Ctx): Promise<any> {
  const input = ctx.input;
  return __project("{ id: id, region: 'north', amount: amount }", input);
}

async function process_south(ctx: Ctx): Promise<any> {
  const input = ctx.input;
  return __project("{ id: id, region: 'south', amount: amount }", input);
}

async function process_east(ctx: Ctx): Promise<any> {
  const input = ctx.input;
  return __project("{ id: id, region: 'east', amount: amount }", input);
}

async function fan_in(ctx: Ctx): Promise<any> {
  const sources: string[] = ["process_north","process_south","process_east"];
  void sources;
  const branches: any[] = ctx.values["fan_out" + ":branches"] ?? [];
  // strategy: all
  if ("all" === "first") return branches[0];
  if ("all" === "majority") {
    const counts = new Map<string, number>();
    for (const b of branches) { const k = JSON.stringify(b); counts.set(k, (counts.get(k) ?? 0) + 1); }
    let best: string | undefined; let bestN = 0;
    for (const [k, n] of counts) if (n > bestN) { bestN = n; best = k; }
    return best ? JSON.parse(best) : null;
  }
  return branches.flat();
}

async function settle_wait(ctx: Ctx): Promise<any> {
  const awaitFn = (globalThis as any).__await;
  const ev = awaitFn ? await Promise.race([
    awaitFn({ topic: "settlement.completed" }, ctx),
    new Promise<any>((resolve) => setTimeout(() => resolve(null), 3600000)),
  ]) : null;
  if (ev === null && "") {
    await __execute("", ctx);
    return ctx.values[""];
  }
  return ev;
}

async function human_review(ctx: Ctx): Promise<any> {
  const gate = (globalThis as any).__gate;
  const decision = gate ? await Promise.race([
    gate({ prompt: "Approve this batch?", options: ["approve","reject"], actor: {"role":"compliance_officer"} }, ctx.input),
    new Promise<any>((resolve) => setTimeout(() => resolve(null), 86400000)),
  ]) : null;
  if (decision === null && "") {
    await __execute("", ctx);
    return ctx.values[""];
  }
  return decision;
}

async function notify_external(ctx: Ctx): Promise<any> {
  const signalFn = (globalThis as any).__signal;
  const r = signalFn ? await Promise.race([
    signalFn("payment-gateway", {"type":"webhook","url":"https://gateway.example.com/notify"}, ctx),
    new Promise<any>((resolve) => setTimeout(() => resolve(null), 30000)),
  ]) : null;
  if (r === null && "") {
    await __execute("", ctx);
    return ctx.values[""];
  }
  return r;
}

class __TerminateError extends Error {
  constructor(public reason: string, public status: string) { super(`__TERMINATE: ${reason}`); }
}
async function __execute(id: string, ctx: Ctx): Promise<void> {
  switch (id) {
    case "fetch_orders": {
      ctx.values["fetch_orders"] = await fetch_orders(ctx);
      return __execute("fan_out", ctx);
    }
    case "fan_out": {
      ctx.values["fan_out"] = await fan_out(ctx);
      return __execute("fan_in", ctx);
    }
    case "process_north": {
      ctx.values["process_north"] = await process_north(ctx);
      return;
    }
    case "process_south": {
      ctx.values["process_south"] = await process_south(ctx);
      return;
    }
    case "process_east": {
      ctx.values["process_east"] = await process_east(ctx);
      return;
    }
    case "fan_in": {
      ctx.values["fan_in"] = await fan_in(ctx);
      return __execute("settle_wait", ctx);
    }
    case "settle_wait": {
      ctx.values["settle_wait"] = await settle_wait(ctx);
      return __execute("human_review", ctx);
    }
    case "human_review": {
      ctx.values["human_review"] = await human_review(ctx);
      return __execute("notify_external", ctx);
    }
    case "notify_external": {
      ctx.values["notify_external"] = await notify_external(ctx);
      return;
    }
    default: throw new Error(`unknown verb id: ${id}`);
  }
}

export async function run(input: any): Promise<Ctx> {
  const ctx = newCtx(input);
  try {
    await __execute("fetch_orders", ctx);
  } catch (e) {
    if (!(e instanceof __TerminateError)) throw e;
  }
  return ctx;
}
