import { BaseResolver, type VerbHandler } from '../core/resolver.js'
import { partitionVerbs, type Composition, type ComputeVerb, type Verb } from '../core/ir.js'

type FetchParams = { source?: { type?: string; config?: { url?: string } } }
type ValidateParams = {
  rules?: unknown[]
  on_fail?: { action?: string; target?: string }
}
type MapParams = { expression?: string; project?: Record<string, string> }
type FilterParams = { predicate?: string }
type ReduceParams = { expression?: string }
type PersistParams = {
  sink?: { type?: string; config?: { table?: string; connection?: unknown } }
  mode?: string
}
type EmitParams = {
  target?: { type?: string; config?: { url?: string; channel?: string } }
}

const HEADER_LINE_1 = '// Generated by NOMARK Intents resolver (target: typescript)'

const PREAMBLE_HELPERS = `import { setTimeout as sleep } from "node:timers/promises";
/** Runtime context passed between verbs — values produced by prior verbs are stored here. */
export interface Ctx {
  input: any;
  values: Record<string, any>;
  receipts: Record<string, { id: string; timestamp: string; sink: string; reversible: boolean }>;
}
function newCtx(input: any): Ctx {
  return { input, values: {}, receipts: {} };
}
async function __retry<T>(fn: () => Promise<T>, max: number, delayMs: number, backoff: "linear"|"exponential", jitter: boolean): Promise<T> {
  let lastErr: unknown;
  for (let attempt = 0; attempt < max; attempt++) {
    try { return await fn(); } catch (e) { lastErr = e; }
    const base = backoff === "exponential" ? delayMs * Math.pow(2, attempt) : delayMs * (attempt + 1);
    const wait = jitter ? base * (0.5 + Math.random()) : base;
    await sleep(wait);
  }
  throw lastErr;
}
function __receipt(sink: string, reversible = true) {
  return { id: crypto.randomUUID(), timestamp: new Date().toISOString(), sink, reversible };
}
/** Minimal predicate evaluator — opaque string per spec §3.1. Resolver chose JS. */
function __predicate(expr: string, row: any): boolean {
  // eslint-disable-next-line no-new-func
  return Boolean(new Function("row", \`return (\${expr});\`)(row));
}
function __project<T>(expr: string, input: T): any {
  // eslint-disable-next-line no-new-func
  return new Function("input", "row", \`return (\${expr});\`)(input, input);
}
function __reduce(expr: string, input: any[], initial: any): any {
  const m = expr.match(/^group_by\\(([^)]+)\\)\\.(sum|count|avg|min|max)\\(([^)]*)\\)$/);
  if (m) {
    const [, key, op, field] = m;
    const groups = new Map<any, any[]>();
    for (const row of input) {
      const k = __project(key, row);
      if (!groups.has(k)) groups.set(k, []);
      groups.get(k)!.push(row);
    }
    const out: Record<string, any> = {};
    for (const [k, rows] of groups) {
      if (op === "count") out[String(k)] = rows.length;
      else {
        const vals = rows.map(r => __project(field, r));
        if (op === "sum") out[String(k)] = vals.reduce((a, b) => a + b, 0);
        else if (op === "avg") out[String(k)] = vals.reduce((a, b) => a + b, 0) / vals.length;
        else if (op === "min") out[String(k)] = Math.min(...vals);
        else if (op === "max") out[String(k)] = Math.max(...vals);
      }
    }
    return out;
  }
  const m2 = expr.match(/^(sum|count|avg|min|max)\\(([^)]*)\\)$/);
  if (m2) {
    const [, op, field] = m2;
    if (op === "count") return input.length;
    const vals = input.map(r => __project(field, r));
    if (op === "sum") return vals.reduce((a, b) => a + b, 0);
    if (op === "avg") return vals.reduce((a, b) => a + b, 0) / vals.length;
    if (op === "min") return Math.min(...vals);
    if (op === "max") return Math.max(...vals);
  }
  // generic reducer: treat expr as JS lambda "acc, row => ..."
  // eslint-disable-next-line no-new-func
  const fn = new Function("acc", "row", \`return (\${expr});\`) as (a: any, r: any) => any;
  return input.reduce(fn, initial);
}`

const CONNECTION_DEFAULT = '{"__rawJs":"process.env.DATABASE_URL"}'

export class TypeScriptBackend extends BaseResolver {
  readonly label = 'typescript'

  protected handlers: Partial<Record<ComputeVerb, VerbHandler>> = {
    FETCH: (v) => this.emitFetch(v),
    VALIDATE: (v) => this.emitValidate(v),
    MAP: (v) => this.emitMap(v),
    FILTER: (v) => this.emitFilter(v),
    REDUCE: (v) => this.emitReduce(v),
    PERSIST: (v) => this.emitPersist(v),
    EMIT: (v) => this.emitEmit(v),
  }

  protected rootFileName(c: Composition): string {
    return `${c.name}.ts`
  }

  protected emitPreamble(c: Composition): string {
    const header = [
      HEADER_LINE_1,
      `// Composition: ${c.name} v${c.version}`,
      `// ${c.description ?? ''}`,
    ].join('\n')
    return `${header}\n${PREAMBLE_HELPERS}`
  }

  protected emitPostamble(c: Composition): string {
    const { compute } = partitionVerbs(c)
    const first = compute[0]?.id ?? 'start'
    const cases = compute
      .map((v, i) => {
        const next = compute[i + 1]
        const follow = next
          ? `return __execute(${JSON.stringify(next.id)}, ctx);`
          : 'return;'
        return `    case ${JSON.stringify(v.id)}: {
      ctx.values[${JSON.stringify(v.id)}] = await ${v.id}(ctx);
      ${follow}
    }`
      })
      .join('\n')

    return `async function __execute(id: string, ctx: Ctx): Promise<void> {
  switch (id) {
${cases}
    default: throw new Error(\`unknown verb id: \${id}\`);
  }
}

export async function run(input: any): Promise<Ctx> {
  const ctx = newCtx(input);
  await __execute(${JSON.stringify(first)}, ctx);
  return ctx;
}
`
  }

  private emitFetch(v: Verb): string {
    const p = (v.params ?? {}) as FetchParams
    const url = p.source?.config?.url ?? ''
    return `async function ${v.id}(ctx: Ctx): Promise<any> {
  const r = await fetch(${JSON.stringify(url)}, {}); return await r.json();
}
`
  }

  private emitValidate(v: Verb): string {
    const p = (v.params ?? {}) as ValidateParams
    const rules = JSON.stringify(p.rules ?? [])
    const action = p.on_fail?.action ?? 'flag'
    const routeTarget = p.on_fail?.target ?? ''
    return `async function ${v.id}(ctx: Ctx): Promise<any> {
  const input = ctx.input;
  const rules: any = ${rules};
  // Basic schema check — host may inject Ajv via globalThis.__validator.
  const v = (globalThis as any).__validator;
  const ok = v ? v(rules)(input) : true;
  if (!ok) {
    const action = ${JSON.stringify(action)};
    if (action === "reject") throw new Error("VALIDATE ${v.id} failed");
    if (action === "route") { await __execute(${JSON.stringify(routeTarget)}, ctx); return ctx.values[${JSON.stringify(routeTarget)}]; }
    if (action === "flag") return { ...input, __flagged: true };
  }
  return input;
}
`
  }

  private emitMap(v: Verb): string {
    const p = (v.params ?? {}) as MapParams
    const expr = p.expression ?? this.projectToExpression(p.project)
    return `async function ${v.id}(ctx: Ctx): Promise<any> {
  const input = ctx.input;
  return __project(${JSON.stringify(expr)}, input);
}
`
  }

  private projectToExpression(project: Record<string, string> | undefined): string {
    if (!project) return 'row'
    const pairs = Object.entries(project).map(([k, expr]) => `${k}: ${expr}`)
    return `{ ${pairs.join(', ')} }`
  }

  private emitFilter(v: Verb): string {
    const p = (v.params ?? {}) as FilterParams
    const pred = p.predicate ?? 'true'
    return `async function ${v.id}(ctx: Ctx): Promise<any[]> {
  const input: any[] = ctx.input ?? [];
  return input.filter(row => __predicate(${JSON.stringify(pred)}, row));
}
`
  }

  private emitReduce(v: Verb): string {
    const p = (v.params ?? {}) as ReduceParams
    const expr = p.expression ?? 'row'
    return `async function ${v.id}(ctx: Ctx): Promise<any> {
  const input: any[] = ctx.input ?? [];
  return __reduce(${JSON.stringify(expr)}, input, null);
}
`
  }

  private emitPersist(v: Verb): string {
    const p = (v.params ?? {}) as PersistParams
    const table = p.sink?.config?.table ?? 'unknown_table'
    const connection = p.sink?.config?.connection
      ? JSON.stringify(p.sink.config.connection)
      : CONNECTION_DEFAULT
    return `async function ${v.id}(ctx: Ctx): Promise<any> {
  const input = ctx.input;
  const { default: pg } = await import("pg");
  const client = new pg.Client(${connection});
  await client.connect();
  try {
    const rows: any[] = Array.isArray(input) ? input : [input];
    for (const row of rows) {
      const keys = Object.keys(row); const vals = Object.values(row);
      const placeholders = keys.map((_, i) => "$" + (i+1)).join(", ");
      const sql = \`INSERT INTO ${table} (\${keys.join(",")}) VALUES (\${placeholders})\`;
      await client.query(sql, vals);
    }
  } finally { await client.end(); }
  const receipt = __receipt("sql:${table}");
  ctx.receipts[${JSON.stringify(v.id)}] = receipt;
  return receipt;
}
`
  }

  private emitEmit(v: Verb): string {
    const p = (v.params ?? {}) as EmitParams
    const url = p.target?.config?.url ?? ''
    const channel = p.target?.config?.channel ?? ''
    return `async function ${v.id}(ctx: Ctx): Promise<any> {
  const payload = ctx.values[${JSON.stringify(v.id)}] ?? ctx.input;
  await fetch(${JSON.stringify(url)}, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ channel: ${JSON.stringify(channel)}, text: typeof payload === "string" ? payload : JSON.stringify(payload) }) });
  // fire-and-forget per spec §3.6
  return;
}
`
  }
}
