-- Generated by NOMARK Intents resolver (target: sql/sqlite)
-- Composition: flow_parallel v0.4.0
-- Parallel fan-out by region, merge results, await settlement, gate on human review, signal external.
BEGIN;
-- FETCH fetch_orders
SELECT * FROM "src";

-- SPLIT fan_out: parallel fan-out handled by host runtime.

-- MAP process_north
CREATE OR REPLACE VIEW v_process_north AS SELECT id AS "id", 'north' AS "region", amount AS "amount" FROM source;

-- MAP process_south
CREATE OR REPLACE VIEW v_process_south AS SELECT id AS "id", 'south' AS "region", amount AS "amount" FROM source;

-- MAP process_east
CREATE OR REPLACE VIEW v_process_east AS SELECT id AS "id", 'east' AS "region", amount AS "amount" FROM source;

-- MERGE fan_in: parallel fan-in handled by host runtime.

-- AWAIT settle_wait: blocking on event/time/signal handled by host runtime.

-- GATE human_review: human-in-the-loop decision handled by host runtime.

-- SIGNAL notify_external: external system dispatch handled by host runtime.
COMMIT;