// Generated by NOMARK Intents resolver (target: react)
// Composition: fund_flow_dashboard v0.4.0
// Read-model dashboard for fund flow monitoring.
import { type ReactNode } from 'react';

export type DashboardState = {
  values: Record<string, unknown>;
  status: 'idle' | 'loading' | 'empty';
  alerts: readonly string[];
};

function outcome(children: ReactNode): ReactNode {
  return (
    <main
      data-monitor='outcome'
      data-subject='fund flows'
      data-refresh='5m'
    >
      {children}
    </main>
  );
}

function layout(children: ReactNode): ReactNode {
  return (
    <div
      data-arrange='grid'
      data-density='compact'
      data-children='metric_aum,chart_flows'
    >
      {children}
    </div>
  );
}

function metric_aum(state: DashboardState): ReactNode {
  return (
    <section data-display='metric_aum' data-type='metric' data-emphasis='hero'>
      <header>Total AUM</header>
      <strong>{String(state.values['aum_total'] ?? '—')}</strong>
    </section>
  );
}

function chart_flows(state: DashboardState): ReactNode {
  return (
    <section data-display='chart_flows' data-type='chart' data-emphasis='standard'>
      <pre>{JSON.stringify(state.values['flow_by_fund'] ?? null, null, 2)}</pre>
    </section>
  );
}

function loading(state: DashboardState): ReactNode {
  if (state.status !== 'loading') return null;
  return (
    <div role='status' aria-live='polite' data-status='loading'>
      Fetching fund flows...
    </div>
  );
}

function anomaly_hint(state: DashboardState): ReactNode {
  if (!state.alerts.includes('anomaly_hint')) return null;
  return (
    <div role='alert' data-guide='anomaly_hint' data-priority='primary'>
      Anomalous outflow detected
    </div>
  );
}

export function Dashboard(state: DashboardState): ReactNode {
  return outcome(
    <>
      {loading(state)}
      {anomaly_hint(state)}
      {layout(
        <>
          {metric_aum(state)}
          {chart_flows(state)}
        </>,
      )}
    </>,
  );
}
