import { BaseResolver, type VerbHandler } from '../core/resolver.js'
import { hasInteractiveVerbs, partitionVerbs, type Composition, type ComputeVerb, type SurfaceVerb, type Verb } from '../core/ir.js'

type MonitorParams = {
  subject?: string
  data?: unknown
  refresh?: { value?: number; unit?: string }
}
type ArrangeParams = { type?: string; density?: string; children?: readonly string[] }
type DisplayParams = { type?: string; data?: string; emphasis?: string; label?: string }
type StatusParams = { type?: string; message?: string }
type GuideParams = { type?: string; message?: string; priority?: string }

type DecideParams = { prompt?: string; options?: { value?: string; label?: string }[] }
type ConfigureParams = { prompt?: string; params?: { key?: string; type?: string; label?: string }[] }
type ExploreParams = { prompt?: string; source?: string; placeholder?: string }
type AuthorParams = { prompt?: string; schema?: string; save_mode?: string }
type OnboardParams = { prompt?: string; steps?: { id?: string; label?: string }[]; progress_type?: string }
type CollectParams = { type?: string; label?: string; name?: string; required?: boolean }

const PREAMBLE_READONLY = `import { type ReactNode } from 'react';

export type DashboardState = {
  values: Record<string, unknown>;
  status: 'idle' | 'loading' | 'empty';
  alerts: readonly string[];
};
`

const PREAMBLE_INTERACTIVE = `import { type ReactNode } from 'react';

export type DashboardState = {
  values: Record<string, unknown>;
  status: 'idle' | 'loading' | 'empty';
  alerts: readonly string[];
  selections: Record<string, unknown>;
  drafts: Record<string, unknown>;
};

export type DashboardDispatch = (event: { verb: string; id: string; action: string; payload: unknown }) => void;
`

export class ReactBackend extends BaseResolver {
  readonly label = 'react'

  /** Set in emitPreamble; consumed by handlers and emitPostamble. */
  private interactive = false

  protected handlers: Partial<Record<ComputeVerb | SurfaceVerb, VerbHandler>> = {
    MONITOR: (v) => this.emitMonitor(v),
    ARRANGE: (v) => this.emitArrange(v),
    DISPLAY: (v) => this.emitDisplay(v),
    STATUS: (v) => this.emitStatus(v),
    GUIDE: (v) => this.emitGuide(v),
    DECIDE: (v) => this.emitDecide(v),
    CONFIGURE: (v) => this.emitConfigure(v),
    EXPLORE: (v) => this.emitExplore(v),
    AUTHOR: (v) => this.emitAuthor(v),
    ONBOARD: (v) => this.emitOnboard(v),
    COLLECT: (v) => this.emitCollect(v),
  }

  protected override handlerKind(): 'compute' | 'surface' {
    return 'surface'
  }

  protected override targetVerbs(c: Composition): { handled: Verb[]; stripped: Verb[] } {
    this.interactive = hasInteractiveVerbs(c)
    const { compute, surface } = partitionVerbs(c)
    return { handled: surface, stripped: compute }
  }

  protected rootFileName(_c: Composition): string {
    return 'Dashboard.tsx'
  }

  protected emitPreamble(c: Composition): string {
    const header = [
      '// Generated by NOMARK Intents resolver (target: react)',
      `// Composition: ${c.name} v${c.version}`,
      `// ${c.description ?? ''}`,
    ].join('\n')
    return `${header}\n${this.interactive ? PREAMBLE_INTERACTIVE : PREAMBLE_READONLY}`
  }

  protected emitPostamble(c: Composition): string {
    const { surface } = partitionVerbs(c)
    const monitor = surface.find((v) => v.verb === 'MONITOR')
    const arrange = surface.find((v) => v.verb === 'ARRANGE')
    const statuses = surface.filter((v) => v.verb === 'STATUS')
    const guides = surface.filter((v) => v.verb === 'GUIDE')

    if (!monitor) throw new Error('React backend requires a MONITOR verb')
    if (!arrange) throw new Error('React backend requires an ARRANGE verb')

    const arrangeParams = (arrange.params ?? {}) as ArrangeParams
    const children = arrangeParams.children ?? []

    if (!this.interactive) {
      const statusLines = statuses.map((s) => `      {${s.id}(state)}`)
      const guideLines = guides.map((g) => `      {${g.id}(state)}`)
      const childLines = children.map((childId) => `          {${childId}(state)}`)
      const lines: string[] = [
        'export function Dashboard(state: DashboardState): ReactNode {',
        `  return ${monitor.id}(`,
        '    <>',
        ...statusLines,
        ...guideLines,
        `      {${arrange.id}(`,
        '        <>',
        ...childLines,
        '        </>,',
        '      )}',
        '    </>,',
        '  );',
        '}',
      ]
      return lines.join('\n') + '\n'
    }

    // Interactive form: pass dispatch alongside state.
    const statusLines = statuses.map((s) => `      {${s.id}(state, dispatch)}`)
    const guideLines = guides.map((g) => `      {${g.id}(state, dispatch)}`)
    const childLines = children.map((childId) => `          {${childId}(state, dispatch)}`)
    const lines: string[] = [
      'export function Dashboard(state: DashboardState, dispatch: DashboardDispatch): ReactNode {',
      `  return ${monitor.id}(`,
      '    <>',
      ...statusLines,
      ...guideLines,
      `      {${arrange.id}(`,
      '        <>',
      ...childLines,
      '        </>,',
      '      )}',
      '    </>,',
      '  );',
      '}',
    ]
    return lines.join('\n') + '\n'
  }

  private emitMonitor(v: Verb): string {
    const p = (v.params ?? {}) as MonitorParams
    const subject = p.subject ?? ''
    const refresh = p.refresh ? `${p.refresh.value}${p.refresh.unit}` : ''
    return `function ${v.id}(children: ReactNode): ReactNode {
  return (
    <main
      data-monitor='${v.id}'
      data-subject='${subject}'
      data-refresh='${refresh}'
    >
      {children}
    </main>
  );
}
`
  }

  private emitArrange(v: Verb): string {
    const p = (v.params ?? {}) as ArrangeParams
    const type = p.type ?? ''
    const density = p.density ?? ''
    const childrenAttr = (p.children ?? []).join(',')
    return `function ${v.id}(children: ReactNode): ReactNode {
  return (
    <div
      data-arrange='${type}'
      data-density='${density}'
      data-children='${childrenAttr}'
    >
      {children}
    </div>
  );
}
`
  }

  private displaySig(): string {
    return this.interactive
      ? `(state: DashboardState, dispatch: DashboardDispatch)`
      : `(state: DashboardState)`
  }

  private emitDisplay(v: Verb): string {
    const p = (v.params ?? {}) as DisplayParams
    const type = p.type ?? ''
    const emphasis = p.emphasis ?? ''
    const dataKey = p.data ?? ''
    const openTag = `<section data-display='${v.id}' data-type='${type}' data-emphasis='${emphasis}'>`
    const sig = this.displaySig()
    if (type === 'metric') {
      const label = p.label ?? ''
      return `function ${v.id}${sig}: ReactNode {
  return (
    ${openTag}
      <header>${label}</header>
      <strong>{String(state.values['${dataKey}'] ?? '—')}</strong>
    </section>
  );
}
`
    }
    if (type === 'chart') {
      return `function ${v.id}${sig}: ReactNode {
  return (
    ${openTag}
      <pre>{JSON.stringify(state.values['${dataKey}'] ?? null, null, 2)}</pre>
    </section>
  );
}
`
    }
    return `function ${v.id}${sig}: ReactNode {
  return (
    ${openTag}
      {/* unhandled DISPLAY.type='${type}' */}
    </section>
  );
}
`
  }

  private emitStatus(v: Verb): string {
    const p = (v.params ?? {}) as StatusParams
    const type = p.type ?? ''
    const message = p.message ?? ''
    return `function ${v.id}${this.displaySig()}: ReactNode {
  if (state.status !== '${type}') return null;
  return (
    <div role='status' aria-live='polite' data-status='${type}'>
      ${message}
    </div>
  );
}
`
  }

  private emitGuide(v: Verb): string {
    const p = (v.params ?? {}) as GuideParams
    const message = p.message ?? ''
    const priority = p.priority ?? ''
    return `function ${v.id}${this.displaySig()}: ReactNode {
  if (!state.alerts.includes('${v.id}')) return null;
  return (
    <div role='alert' data-guide='${v.id}' data-priority='${priority}'>
      ${message}
    </div>
  );
}
`
  }

  private emitDecide(v: Verb): string {
    const p = (v.params ?? {}) as DecideParams
    const prompt = p.prompt ?? ''
    const opts = p.options ?? []
    const buttons = opts.map((o) =>
      `      <button
        type='button'
        data-option='${o.value ?? ''}'
        onClick={() => dispatch({ verb: 'DECIDE', id: '${v.id}', action: 'select', payload: '${o.value ?? ''}' })}
      >
        ${o.label ?? ''}
      </button>`,
    ).join('\n')
    return `function ${v.id}(state: DashboardState, dispatch: DashboardDispatch): ReactNode {
  return (
    <form data-decide='${v.id}' data-prompt='${prompt}'>
${buttons}
    </form>
  );
}
`
  }

  private emitConfigure(v: Verb): string {
    const p = (v.params ?? {}) as ConfigureParams
    const prompt = p.prompt ?? ''
    const params = p.params ?? []
    const inputs = params.map((pa) =>
      `      <label>
        ${pa.label ?? ''}
        <input
          name='${pa.key ?? ''}'
          type='${pa.type ?? 'text'}'
          defaultValue={String(state.drafts['${pa.key ?? ''}'] ?? state.values['${pa.key ?? ''}'] ?? '')}
          onChange={(e) => dispatch({ verb: 'CONFIGURE', id: '${v.id}', action: 'set', payload: { ${pa.key ?? ''}: e.currentTarget.value } })}
        />
      </label>`,
    ).join('\n')
    return `function ${v.id}(state: DashboardState, dispatch: DashboardDispatch): ReactNode {
  return (
    <form data-configure='${v.id}' data-prompt='${prompt}'>
${inputs}
      <button type='button' onClick={() => dispatch({ verb: 'CONFIGURE', id: '${v.id}', action: 'apply', payload: state.drafts })}>Apply</button>
    </form>
  );
}
`
  }

  private emitExplore(v: Verb): string {
    const p = (v.params ?? {}) as ExploreParams
    const prompt = p.prompt ?? ''
    const source = p.source ?? ''
    const placeholder = p.placeholder ?? ''
    return `function ${v.id}(state: DashboardState, dispatch: DashboardDispatch): ReactNode {
  const results = (state.values['${source}'] as readonly { id: string; label: string }[] | undefined) ?? [];
  return (
    <section data-explore='${v.id}' data-prompt='${prompt}' data-source='${source}'>
      <input
        type='search'
        placeholder='${placeholder}'
        defaultValue={String(state.drafts['${v.id}'] ?? '')}
        onChange={(e) => dispatch({ verb: 'EXPLORE', id: '${v.id}', action: 'query', payload: e.currentTarget.value })}
      />
      <ul role='listbox'>
        {results.map((r) => (
          <li key={r.id} data-result-id={r.id}>{r.label}</li>
        ))}
      </ul>
    </section>
  );
}
`
  }

  private emitAuthor(v: Verb): string {
    const p = (v.params ?? {}) as AuthorParams
    const prompt = p.prompt ?? ''
    const schema = p.schema ?? ''
    const saveMode = p.save_mode ?? 'manual'
    return `function ${v.id}(state: DashboardState, dispatch: DashboardDispatch): ReactNode {
  return (
    <form data-author='${v.id}' data-prompt='${prompt}' data-schema='${schema}' data-save-mode='${saveMode}'>
      <output data-schema-ref='${schema}'>
        {String(state.drafts['${v.id}'] ?? state.values['${v.id}'] ?? '')}
      </output>
      <textarea
        name='${v.id}'
        defaultValue={String(state.drafts['${v.id}'] ?? state.values['${v.id}'] ?? '')}
        onChange={(e) => dispatch({ verb: 'AUTHOR', id: '${v.id}', action: 'edit', payload: e.currentTarget.value })}
      />
      <button type='button' onClick={() => dispatch({ verb: 'AUTHOR', id: '${v.id}', action: 'save', payload: state.drafts['${v.id}'] })}>Save</button>
    </form>
  );
}
`
  }

  private emitOnboard(v: Verb): string {
    const p = (v.params ?? {}) as OnboardParams
    const prompt = p.prompt ?? ''
    const progressType = p.progress_type ?? 'step'
    const steps = p.steps ?? []
    const stepLines = steps.map((s) =>
      `        <li data-step='${s.id ?? ''}' data-active={String(current === '${s.id ?? ''}')}>${s.label ?? ''}</li>`,
    ).join('\n')
    const firstStep = steps[0]?.id ?? ''
    return `function ${v.id}(state: DashboardState, dispatch: DashboardDispatch): ReactNode {
  const current = String(state.selections['${v.id}'] ?? '${firstStep}');
  return (
    <nav data-onboard='${v.id}' data-prompt='${prompt}' data-progress-type='${progressType}'>
      <ol>
${stepLines}
      </ol>
      <button type='button' data-step-action='advance' onClick={() => dispatch({ verb: 'ONBOARD', id: '${v.id}', action: 'advance', payload: current })}>Next</button>
      <button type='button' data-step-action='skip' onClick={() => dispatch({ verb: 'ONBOARD', id: '${v.id}', action: 'skip', payload: current })}>Skip</button>
    </nav>
  );
}
`
  }

  private emitCollect(v: Verb): string {
    const p = (v.params ?? {}) as CollectParams
    const type = p.type ?? 'text'
    const label = p.label ?? ''
    const name = p.name ?? ''
    const required = p.required ?? false
    return `function ${v.id}(state: DashboardState, dispatch: DashboardDispatch): ReactNode {
  return (
    <label data-collect='${v.id}' data-collect-type='${type}'>
      ${label}
      <input
        type='${type}'
        name='${name}'
        required={${required}}
        defaultValue={String(state.drafts['${name}'] ?? '')}
        onChange={(e) => dispatch({ verb: 'COLLECT', id: '${v.id}', action: 'input', payload: e.currentTarget.value })}
      />
    </label>
  );
}
`
  }
}
