import { BaseResolver, type VerbHandler } from '../core/resolver.js'
import { partitionVerbs, type Composition, type ComputeVerb, type SurfaceVerb, type Verb } from '../core/ir.js'

type MonitorParams = {
  subject?: string
  data?: unknown
  refresh?: { value?: number; unit?: string }
}
type ArrangeParams = { type?: string; density?: string; children?: readonly string[] }
type DisplayParams = { type?: string; data?: string; emphasis?: string; label?: string }
type StatusParams = { type?: string; message?: string }
type GuideParams = { type?: string; message?: string; priority?: string }

const PREAMBLE_HELPERS = `import { type ReactNode } from 'react';

export type DashboardState = {
  values: Record<string, unknown>;
  status: 'idle' | 'loading' | 'empty';
  alerts: readonly string[];
};
`

export class ReactBackend extends BaseResolver {
  readonly label = 'react'

  protected handlers: Partial<Record<ComputeVerb | SurfaceVerb, VerbHandler>> = {
    MONITOR: (v) => this.emitMonitor(v),
    ARRANGE: (v) => this.emitArrange(v),
    DISPLAY: (v) => this.emitDisplay(v),
    STATUS: (v) => this.emitStatus(v),
    GUIDE: (v) => this.emitGuide(v),
  }

  protected override handlerKind(): 'compute' | 'surface' {
    return 'surface'
  }

  protected override targetVerbs(c: Composition): { handled: Verb[]; stripped: Verb[] } {
    const { compute, surface } = partitionVerbs(c)
    return { handled: surface, stripped: compute }
  }

  protected rootFileName(_c: Composition): string {
    return 'Dashboard.tsx'
  }

  protected emitPreamble(c: Composition): string {
    const header = [
      '// Generated by NOMARK Intents resolver (target: react)',
      `// Composition: ${c.name} v${c.version}`,
      `// ${c.description ?? ''}`,
    ].join('\n')
    return `${header}\n${PREAMBLE_HELPERS}`
  }

  protected emitPostamble(c: Composition): string {
    const { surface } = partitionVerbs(c)
    const monitor = surface.find((v) => v.verb === 'MONITOR')
    const arrange = surface.find((v) => v.verb === 'ARRANGE')
    const statuses = surface.filter((v) => v.verb === 'STATUS')
    const guides = surface.filter((v) => v.verb === 'GUIDE')

    if (!monitor) throw new Error('React backend requires a MONITOR verb')
    if (!arrange) throw new Error('React backend requires an ARRANGE verb')

    const arrangeParams = (arrange.params ?? {}) as ArrangeParams
    const children = arrangeParams.children ?? []

    const statusLines = statuses.map((s) => `      {${s.id}(state)}`)
    const guideLines = guides.map((g) => `      {${g.id}(state)}`)
    const childLines = children.map((childId) => `          {${childId}(state)}`)

    const lines: string[] = [
      'export function Dashboard(state: DashboardState): ReactNode {',
      `  return ${monitor.id}(`,
      '    <>',
      ...statusLines,
      ...guideLines,
      `      {${arrange.id}(`,
      '        <>',
      ...childLines,
      '        </>,',
      '      )}',
      '    </>,',
      '  );',
      '}',
    ]

    return lines.join('\n') + '\n'
  }

  private emitMonitor(v: Verb): string {
    const p = (v.params ?? {}) as MonitorParams
    const subject = p.subject ?? ''
    const refresh = p.refresh ? `${p.refresh.value}${p.refresh.unit}` : ''
    return `function ${v.id}(children: ReactNode): ReactNode {
  return (
    <main
      data-monitor='${v.id}'
      data-subject='${subject}'
      data-refresh='${refresh}'
    >
      {children}
    </main>
  );
}
`
  }

  private emitArrange(v: Verb): string {
    const p = (v.params ?? {}) as ArrangeParams
    const type = p.type ?? ''
    const density = p.density ?? ''
    const childrenAttr = (p.children ?? []).join(',')
    return `function ${v.id}(children: ReactNode): ReactNode {
  return (
    <div
      data-arrange='${type}'
      data-density='${density}'
      data-children='${childrenAttr}'
    >
      {children}
    </div>
  );
}
`
  }

  private emitDisplay(v: Verb): string {
    const p = (v.params ?? {}) as DisplayParams
    const type = p.type ?? ''
    const emphasis = p.emphasis ?? ''
    const dataKey = p.data ?? ''
    const openTag = `<section data-display='${v.id}' data-type='${type}' data-emphasis='${emphasis}'>`
    if (type === 'metric') {
      const label = p.label ?? ''
      return `function ${v.id}(state: DashboardState): ReactNode {
  return (
    ${openTag}
      <header>${label}</header>
      <strong>{String(state.values['${dataKey}'] ?? '—')}</strong>
    </section>
  );
}
`
    }
    if (type === 'chart') {
      return `function ${v.id}(state: DashboardState): ReactNode {
  return (
    ${openTag}
      <pre>{JSON.stringify(state.values['${dataKey}'] ?? null, null, 2)}</pre>
    </section>
  );
}
`
    }
    return `function ${v.id}(state: DashboardState): ReactNode {
  return (
    ${openTag}
      {/* unhandled DISPLAY.type='${type}' */}
    </section>
  );
}
`
  }

  private emitStatus(v: Verb): string {
    const p = (v.params ?? {}) as StatusParams
    const type = p.type ?? ''
    const message = p.message ?? ''
    return `function ${v.id}(state: DashboardState): ReactNode {
  if (state.status !== '${type}') return null;
  return (
    <div role='status' aria-live='polite' data-status='${type}'>
      ${message}
    </div>
  );
}
`
  }

  private emitGuide(v: Verb): string {
    const p = (v.params ?? {}) as GuideParams
    const message = p.message ?? ''
    const priority = p.priority ?? ''
    return `function ${v.id}(state: DashboardState): ReactNode {
  if (!state.alerts.includes('${v.id}')) return null;
  return (
    <div role='alert' data-guide='${v.id}' data-priority='${priority}'>
      ${message}
    </div>
  );
}
`
  }
}
