import { BaseResolver, type ResolverWarning, type VerbHandler } from '../core/resolver.js'
import type { Composition, ComputeVerb, Verb } from '../core/ir.js'

type MapParams = { project?: Record<string, string> }
type FilterParams = { predicate?: string }
type ReduceParams = {
  group_by?: string | string[]
  agg?: Record<string, string>
}
type PersistParams = {
  sink?: { config?: { table?: string } }
  mode?: string
}

/** Fixed-spec warning emitted for every EMIT verb in SQL output.
 *  Matches the manifest fixture byte-for-byte — do not rephrase. */
export const SQL_EMIT_WARNING = (verbId: string): ResolverWarning => ({
  code: 'VERB_UNEXPRESSIBLE_IN_SQL',
  message: `verb EMIT (${verbId}) cannot be expressed in SQL compute — add a host layer to drive this step`,
  verb_id: verbId,
})

type DialectConfig = {
  label: string
  headerTarget: string
  quote: (ident: string) => string
  placeholder: string
  emitView: (name: string, body: string) => string
}

const POSTGRES: DialectConfig = {
  label: 'sql-postgres',
  headerTarget: 'sql/postgres',
  quote: (i) => `"${i}"`,
  placeholder: '$1',
  emitView: (name, body) => `CREATE OR REPLACE VIEW ${name} AS ${body};`,
}

const SQLITE: DialectConfig = {
  label: 'sql-sqlite',
  headerTarget: 'sql/sqlite',
  quote: (i) => `"${i}"`,
  placeholder: '?',
  emitView: (name, body) => `CREATE OR REPLACE VIEW ${name} AS ${body};`,
}

const MYSQL: DialectConfig = {
  label: 'sql-mysql',
  headerTarget: 'sql/mysql',
  quote: (i) => `\`${i}\``,
  placeholder: '?',
  emitView: (name, body) => `DROP VIEW IF EXISTS ${name};\nCREATE VIEW ${name} AS ${body};`,
}

abstract class SqlBase extends BaseResolver {
  protected abstract readonly dialect: DialectConfig

  get label(): string {
    return this.dialect.label
  }

  protected handlers: Partial<Record<ComputeVerb, VerbHandler>> = {
    FETCH: (v) => this.emitFetch(v),
    VALIDATE: (v) => this.emitValidate(v),
    MAP: (v) => this.emitMap(v),
    FILTER: (v) => this.emitFilter(v),
    REDUCE: (v) => this.emitReduce(v),
    PERSIST: (v) => this.emitPersist(v),
    EMIT: (v, ctx) => {
      ctx.warn(SQL_EMIT_WARNING(v.id))
      return this.emitEmit(v)
    },
  }

  protected override bodySeparator(): string {
    return '\n\n'
  }

  protected rootFileName(c: Composition): string {
    return `${c.name}.sql`
  }

  protected emitPreamble(c: Composition): string {
    return `-- Generated by NOMARK Intents resolver (target: ${this.dialect.headerTarget})
-- Composition: ${c.name} v${c.version}
-- ${c.description ?? ''}
BEGIN;`
  }

  protected emitPostamble(_c: Composition): string {
    return `COMMIT;`
  }

  private emitFetch(v: Verb): string {
    return `-- FETCH ${v.id}\nSELECT * FROM ${this.dialect.quote('src')};`
  }

  private emitValidate(v: Verb): string {
    return `-- VALIDATE ${v.id}: rules must be enforced by host or CHECK constraints at schema time.`
  }

  private emitMap(v: Verb): string {
    const p = (v.params ?? {}) as MapParams
    const project = p.project ?? {}
    const columns = Object.entries(project)
      .map(([alias, expr]) => `${expr} AS ${this.dialect.quote(alias)}`)
      .join(', ')
    const body = `SELECT ${columns} FROM source`
    return `-- MAP ${v.id}\n${this.dialect.emitView(`v_${v.id}`, body)}`
  }

  private emitFilter(v: Verb): string {
    const p = (v.params ?? {}) as FilterParams
    const pred = p.predicate ?? 'TRUE'
    const body = `SELECT * FROM source WHERE ${pred}`
    return `-- FILTER ${v.id}\n${this.dialect.emitView(`v_${v.id}`, body)}`
  }

  private emitReduce(v: Verb): string {
    const p = (v.params ?? {}) as ReduceParams
    const keys = Array.isArray(p.group_by) ? p.group_by : p.group_by ? [p.group_by] : []
    const aggs = Object.entries(p.agg ?? {}).map(
      ([alias, expr]) => `${expr} AS ${this.dialect.quote(alias)}`,
    )
    const selectCols = [
      ...keys.map((k) => this.dialect.quote(k)),
      ...aggs,
    ].join(', ')
    const groupCols = keys.map((k) => this.dialect.quote(k)).join(', ')
    const body = `SELECT ${selectCols} FROM source GROUP BY ${groupCols}`
    return `-- REDUCE ${v.id}\n${this.dialect.emitView(`v_${v.id}`, body)}`
  }

  private emitPersist(v: Verb): string {
    const p = (v.params ?? {}) as PersistParams
    const table = p.sink?.config?.table ?? 'unknown_table'
    const mode = p.mode ?? 'insert'
    return `-- PERSIST ${v.id} (mode: ${mode})
INSERT INTO ${this.dialect.quote(table)} (${this.dialect.quote('*unknown_columns*')}) VALUES (${this.dialect.placeholder});`
  }

  private emitEmit(v: Verb): string {
    return `-- EMIT (${v.id}) not expressible as SQL. Host runtime required.`
  }
}

export class PostgresBackend extends SqlBase {
  protected readonly dialect = POSTGRES
}

export class SqliteBackend extends SqlBase {
  protected readonly dialect = SQLITE
}

export class MysqlBackend extends SqlBase {
  protected readonly dialect = MYSQL
}
