-- Generated by NOMARK Intents resolver (target: sql/postgres)
-- Composition: resilient_etl v0.4.0
-- ETL with retried fetch, error-handled validate, persisted records, and a compensating undo for the persist step.
BEGIN;
-- RETRY fetch_with_retry: not expressible in SQL compute. Host runtime required.

-- ERROR safe_validate: try/catch + handler routing handled by host runtime.

-- PERSIST persist_data (mode: insert)
INSERT INTO "records" ("*unknown_columns*") VALUES ($1);

-- COMPENSATE rollback_persist: receipt tracking + reverse op handled by host runtime.
COMMIT;