<!-- Generated by NOMARK Intents resolver (target: svelte) -->
<!-- Composition: fund_flow_dashboard v0.4.0 -->
<!-- Read-model dashboard for fund flow monitoring. -->
<script lang="ts" module>
  export type DashboardState = {
    values: Record<string, unknown>;
    status: 'idle' | 'loading' | 'empty';
    alerts: readonly string[];
  };
</script>

<script lang="ts">
  let { state }: { state: DashboardState } = $props();
</script>

{#snippet metric_aum(state: DashboardState)}
  <section data-display='metric_aum' data-type='metric' data-emphasis='hero'>
    <header>Total AUM</header>
    <strong>{String(state.values['aum_total'] ?? '—')}</strong>
  </section>
{/snippet}

{#snippet chart_flows(state: DashboardState)}
  <section data-display='chart_flows' data-type='chart' data-emphasis='standard'>
    <pre>{JSON.stringify(state.values['flow_by_fund'] ?? null, null, 2)}</pre>
  </section>
{/snippet}

{#snippet loading(state: DashboardState)}
  {#if state.status === 'loading'}
    <div role='status' aria-live='polite' data-status='loading'>
      Fetching fund flows...
    </div>
  {/if}
{/snippet}

{#snippet anomaly_hint(state: DashboardState)}
  {#if state.alerts.includes('anomaly_hint')}
    <div role='alert' data-guide='anomaly_hint' data-priority='primary'>
      Anomalous outflow detected
    </div>
  {/if}
{/snippet}

{#snippet layout(state: DashboardState)}
  <div
    data-arrange='grid'
    data-density='compact'
    data-children='metric_aum,chart_flows'
  >
    {@render metric_aum(state)}
    {@render chart_flows(state)}
  </div>
{/snippet}

{#snippet outcome(state: DashboardState)}
  <main
    data-monitor='outcome'
    data-subject='fund flows'
    data-refresh='5m'
  >
    {@render loading(state)}
    {@render anomaly_hint(state)}
    {@render layout(state)}
  </main>
{/snippet}

{@render outcome(state)}
