"""
Generated by NOMARK Intents resolver (target: python).
Composition: flow_parallel v0.4.0
Parallel fan-out by region, merge results, await settlement, gate on human review, signal external.
"""
from __future__ import annotations
import asyncio
import dataclasses
import json
import os
import random
import re
import time
import uuid
from typing import Any, Callable, Dict, List, Optional
@dataclasses.dataclass
class Ctx:
    input: Any = None
    values: Dict[str, Any] = dataclasses.field(default_factory=dict)
    receipts: Dict[str, Dict[str, Any]] = dataclasses.field(default_factory=dict)
async def _retry(fn: Callable[[], Any], max_attempts: int, delay_ms: int,
                 backoff: str = "exponential", jitter: bool = False) -> Any:
    last_err: Optional[BaseException] = None
    for attempt in range(max_attempts):
        try:
            return await fn()
        except Exception as e:
            last_err = e
        base = delay_ms * (2 ** attempt) if backoff == "exponential" else delay_ms * (attempt + 1)
        wait = base * (0.5 + random.random()) if jitter else base
        await asyncio.sleep(wait / 1000.0)
    raise last_err  # type: ignore[misc]
def _receipt(sink: str, reversible: bool = True) -> Dict[str, Any]:
    return {
        "id": str(uuid.uuid4()),
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "sink": sink,
        "reversible": reversible,
    }
def _predicate(expr: str, row: Any) -> bool:
    """Opaque expression evaluator — spec §3.1. Resolver chose Python eval."""
    return bool(eval(expr, {"__builtins__": {}}, {"row": row, "r": row}))
def _project(expr: str, input: Any) -> Any:
    return eval(expr, {"__builtins__": {"len": len, "sum": sum, "min": min, "max": max}},
                {"input": input, "row": input, "r": input})
def _reduce(expr: str, items: List[Any], initial: Any) -> Any:
    m = re.match(r"^group_by\(([^)]+)\)\.(sum|count|avg|min|max)\(([^)]*)\)$", expr)
    if m:
        key_expr, op, field = m.group(1), m.group(2), m.group(3)
        groups: Dict[Any, List[Any]] = {}
        for row in items:
            k = _project(key_expr, row)
            groups.setdefault(k, []).append(row)
        out: Dict[str, Any] = {}
        for k, rows in groups.items():
            if op == "count":
                out[str(k)] = len(rows)
                continue
            vals = [_project(field, r) for r in rows]
            if op == "sum": out[str(k)] = sum(vals)
            elif op == "avg": out[str(k)] = sum(vals) / len(vals)
            elif op == "min": out[str(k)] = min(vals)
            elif op == "max": out[str(k)] = max(vals)
        return out
    m2 = re.match(r"^(sum|count|avg|min|max)\(([^)]*)\)$", expr)
    if m2:
        op, field = m2.group(1), m2.group(2)
        if op == "count": return len(items)
        vals = [_project(field, r) for r in items]
        if op == "sum": return sum(vals)
        if op == "avg": return sum(vals) / len(vals) if vals else 0
        if op == "min": return min(vals) if vals else None
        if op == "max": return max(vals) if vals else None
    # generic lambda fallback: expr must name 'acc' and 'row'
    acc = initial
    for row in items:
        acc = eval(expr, {"__builtins__": {}}, {"acc": acc, "row": row})
    return acc
async def fetch_orders(ctx: Ctx) -> Any:
    import httpx
    async with httpx.AsyncClient() as client:
        r = await client.request("GET", "https://api.example.com/orders", json=None)
        r.raise_for_status()
        return r.json()


async def fan_out(ctx: Ctx) -> List[Any]:
    targets = ["process_north", "process_south", "process_east"]
    strategy = "parallel"
    _ = strategy  # 'parallel' | 'broadcast' | 'partition' — host may inspect
    async def _branch(t: str) -> Any:
        branch_ctx = Ctx(input=ctx.input)
        await _execute(t, branch_ctx)
        return branch_ctx.values.get(t)
    results = await asyncio.gather(*[_branch(t) for t in targets])
    ctx.values["fan_out" + ":branches"] = list(results)
    return list(results)


async def process_north(ctx: Ctx) -> Any:
    input = ctx.input
    return _project("{ id: id, region: 'north', amount: amount }", input)


async def process_south(ctx: Ctx) -> Any:
    input = ctx.input
    return _project("{ id: id, region: 'south', amount: amount }", input)


async def process_east(ctx: Ctx) -> Any:
    input = ctx.input
    return _project("{ id: id, region: 'east', amount: amount }", input)


async def fan_in(ctx: Ctx) -> Any:
    sources = ["process_north", "process_south", "process_east"]
    _ = sources
    branches = ctx.values.get("fan_out" + ":branches", [])
    if "all" == "first":
        return branches[0] if branches else None
    if "all" == "majority":
        from collections import Counter
        counts = Counter(json.dumps(b, sort_keys=True) for b in branches)
        if not counts: return None
        return json.loads(counts.most_common(1)[0][0])
    flat: List[Any] = []
    for b in branches:
        if isinstance(b, list): flat.extend(b)
        else: flat.append(b)
    return flat


async def settle_wait(ctx: Ctx) -> Any:
    await_fn = globals().get("__await__")
    ev = None
    if await_fn:
        try:
            ev = await asyncio.wait_for(await_fn({"topic": "settlement.completed"}, ctx), timeout=3600)
        except asyncio.TimeoutError:
            ev = None
    if ev is None and "":
        await _execute("", ctx)
        return ctx.values.get("")
    return ev


async def human_review(ctx: Ctx) -> Any:
    gate = globals().get("__gate__")
    decision = None
    if gate:
        try:
            decision = await asyncio.wait_for(
                gate({"prompt": "Approve this batch?", "options": ["approve", "reject"], "actor": {"role": "compliance_officer"}}, ctx.input),
                timeout=86400,
            )
        except asyncio.TimeoutError:
            decision = None
    if decision is None and "":
        await _execute("", ctx)
        return ctx.values.get("")
    return decision


async def notify_external(ctx: Ctx) -> Any:
    signal_fn = globals().get("__signal__")
    r = None
    if signal_fn:
        try:
            r = await asyncio.wait_for(signal_fn("payment-gateway", {"type": "webhook", "url": "https://gateway.example.com/notify"}, ctx), timeout=30)
        except asyncio.TimeoutError:
            r = None
    if r is None and "":
        await _execute("", ctx)
        return ctx.values.get("")
    return r

class _TerminateError(Exception):
    def __init__(self, reason: str, status: str):
        super().__init__(f"__TERMINATE: {reason}")
        self.reason = reason
        self.status = status

async def _execute(vid: str, ctx: Ctx) -> None:
    if vid == "fetch_orders":
        ctx.values["fetch_orders"] = await fetch_orders(ctx)
        await _execute("fan_out", ctx)
        return
    if vid == "fan_out":
        ctx.values["fan_out"] = await fan_out(ctx)
        await _execute("fan_in", ctx)
        return
    if vid == "process_north":
        ctx.values["process_north"] = await process_north(ctx)
        return
        return
    if vid == "process_south":
        ctx.values["process_south"] = await process_south(ctx)
        return
        return
    if vid == "process_east":
        ctx.values["process_east"] = await process_east(ctx)
        return
        return
    if vid == "fan_in":
        ctx.values["fan_in"] = await fan_in(ctx)
        await _execute("settle_wait", ctx)
        return
    if vid == "settle_wait":
        ctx.values["settle_wait"] = await settle_wait(ctx)
        await _execute("human_review", ctx)
        return
    if vid == "human_review":
        ctx.values["human_review"] = await human_review(ctx)
        await _execute("notify_external", ctx)
        return
    if vid == "notify_external":
        ctx.values["notify_external"] = await notify_external(ctx)
        return
        return
    raise ValueError(f"unknown verb id: {vid}")

async def run(input: Any = None) -> Ctx:
    ctx = Ctx(input=input)
    try:
        await _execute("fetch_orders", ctx)
    except _TerminateError:
        pass
    return ctx


if __name__ == "__main__":
    asyncio.run(run())
