-- Generated by NOMARK Intents resolver (target: sql/sqlite)
-- Composition: daily_fund_flow_etl v0.4.0
-- Pull daily fund flow rows from an HTTP source, validate, normalize, aggregate per fund, upsert into Postgres, then notify on completion.
BEGIN;
-- FETCH fetch_rows
SELECT * FROM "src";

-- VALIDATE validate_rows: rules must be enforced by host or CHECK constraints at schema time.

-- MAP normalize_region
CREATE OR REPLACE VIEW v_normalize_region AS SELECT fund_id AS "fund_id", trade_date AS "trade_date", flow_usd AS "flow_usd", region AS "region" FROM source;

-- FILTER drop_zero
CREATE OR REPLACE VIEW v_drop_zero AS SELECT * FROM source WHERE flow_usd != 0;

-- REDUCE aggregate_daily
CREATE OR REPLACE VIEW v_aggregate_daily AS SELECT "fund_id", "trade_date", sum(flow_usd) AS "total_flow_usd", count(*) AS "row_count" FROM source GROUP BY "fund_id", "trade_date";

-- PERSIST upsert_daily (mode: insert)
INSERT INTO "fund_flow_daily" ("*unknown_columns*") VALUES (?);

-- EMIT (notify_done) not expressible as SQL. Host runtime required.
COMMIT;