// Generated by NOMARK Intents resolver (target: typescript)
// Composition: resilient_etl v0.4.0
// ETL with retried fetch, error-handled validate, persisted records, and a compensating undo for the persist step.
import { setTimeout as sleep } from "node:timers/promises";
/** Runtime context passed between verbs — values produced by prior verbs are stored here. */
export interface Ctx {
  input: any;
  values: Record<string, any>;
  receipts: Record<string, { id: string; timestamp: string; sink: string; reversible: boolean }>;
}
function newCtx(input: any): Ctx {
  return { input, values: {}, receipts: {} };
}
async function __retry<T>(fn: () => Promise<T>, max: number, delayMs: number, backoff: "linear"|"exponential", jitter: boolean): Promise<T> {
  let lastErr: unknown;
  for (let attempt = 0; attempt < max; attempt++) {
    try { return await fn(); } catch (e) { lastErr = e; }
    const base = backoff === "exponential" ? delayMs * Math.pow(2, attempt) : delayMs * (attempt + 1);
    const wait = jitter ? base * (0.5 + Math.random()) : base;
    await sleep(wait);
  }
  throw lastErr;
}
function __receipt(sink: string, reversible = true) {
  return { id: crypto.randomUUID(), timestamp: new Date().toISOString(), sink, reversible };
}
/** Minimal predicate evaluator — opaque string per spec §3.1. Resolver chose JS. */
function __predicate(expr: string, row: any): boolean {
  // eslint-disable-next-line no-new-func
  return Boolean(new Function("row", `return (${expr});`)(row));
}
function __project<T>(expr: string, input: T): any {
  // eslint-disable-next-line no-new-func
  return new Function("input", "row", `return (${expr});`)(input, input);
}
function __reduce(expr: string, input: any[], initial: any): any {
  const m = expr.match(/^group_by\(([^)]+)\)\.(sum|count|avg|min|max)\(([^)]*)\)$/);
  if (m) {
    const [, key, op, field] = m;
    const groups = new Map<any, any[]>();
    for (const row of input) {
      const k = __project(key, row);
      if (!groups.has(k)) groups.set(k, []);
      groups.get(k)!.push(row);
    }
    const out: Record<string, any> = {};
    for (const [k, rows] of groups) {
      if (op === "count") out[String(k)] = rows.length;
      else {
        const vals = rows.map(r => __project(field, r));
        if (op === "sum") out[String(k)] = vals.reduce((a, b) => a + b, 0);
        else if (op === "avg") out[String(k)] = vals.reduce((a, b) => a + b, 0) / vals.length;
        else if (op === "min") out[String(k)] = Math.min(...vals);
        else if (op === "max") out[String(k)] = Math.max(...vals);
      }
    }
    return out;
  }
  const m2 = expr.match(/^(sum|count|avg|min|max)\(([^)]*)\)$/);
  if (m2) {
    const [, op, field] = m2;
    if (op === "count") return input.length;
    const vals = input.map(r => __project(field, r));
    if (op === "sum") return vals.reduce((a, b) => a + b, 0);
    if (op === "avg") return vals.reduce((a, b) => a + b, 0) / vals.length;
    if (op === "min") return Math.min(...vals);
    if (op === "max") return Math.max(...vals);
  }
  // generic reducer: treat expr as JS lambda "acc, row => ..."
  // eslint-disable-next-line no-new-func
  const fn = new Function("acc", "row", `return (${expr});`) as (a: any, r: any) => any;
  return input.reduce(fn, initial);
}
async function fetch_with_retry(ctx: Ctx): Promise<any> {
  return await __retry(async () => {
    const r = await fetch("https://api.example.com/records", {}); return await r.json();
  }, 3, 1000, "exponential", true);
}

async function safe_validate(ctx: Ctx): Promise<any> {
  try {
    const rules: any = [{"field":"id","check":"required"}];
    const v = (globalThis as any).__validator;
    const ok = v ? v(rules)(ctx.input) : true;
    if (!ok) throw new Error("VALIDATE failed (action=reject)");
    return ctx.input;
  } catch (e: any) {
    const catches: string[] = ["ValidationError","ValueError"];
    const matches = catches.some(t => e?.name === t || e?.code === t || (e?.constructor?.name === t));
    if (matches) {
      const payload = ctx.input;
      await fetch("", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ channel: "#alerts", text: typeof payload === "string" ? payload : JSON.stringify(payload) }) });
      return;
    }
    throw e;
  }
}

async function persist_data(ctx: Ctx): Promise<any> {
  const input = ctx.input;
  const { default: pg } = await import("pg");
  const client = new pg.Client({"__rawJs":"process.env.DATABASE_URL"});
  await client.connect();
  try {
    const rows: any[] = Array.isArray(input) ? input : [input];
    for (const row of rows) {
      const keys = Object.keys(row); const vals = Object.values(row);
      const placeholders = keys.map((_, i) => "$" + (i+1)).join(", ");
      const sql = `INSERT INTO records (${keys.join(",")}) VALUES (${placeholders})`;
      await client.query(sql, vals);
    }
  } finally { await client.end(); }
  const receipt = __receipt("sql:records");
  ctx.receipts["persist_data"] = receipt;
  return receipt;
}

async function rollback_persist(ctx: Ctx): Promise<any> {
  const receipt = ctx.receipts["persist_data"];
  if (!receipt) throw new Error("COMPENSATE rollback_persist: no receipt for persist_data");
  if (!receipt.reversible) throw new Error("COMPENSATE rollback_persist: receipt is non-reversible");
  const { default: pg } = await import("pg");
  const client = new pg.Client({"__rawJs":"process.env.DATABASE_URL"});
  await client.connect();
  try {
    await client.query(`DELETE FROM records WHERE id = $1`);
  } finally { await client.end(); }
  return __receipt("sql:records", false);
}

async function __execute(id: string, ctx: Ctx): Promise<void> {
  switch (id) {
    case "fetch_with_retry": {
      ctx.values["fetch_with_retry"] = await fetch_with_retry(ctx);
      return __execute("safe_validate", ctx);
    }
    case "safe_validate": {
      ctx.values["safe_validate"] = await safe_validate(ctx);
      return __execute("persist_data", ctx);
    }
    case "persist_data": {
      ctx.values["persist_data"] = await persist_data(ctx);
      return __execute("rollback_persist", ctx);
    }
    case "rollback_persist": {
      ctx.values["rollback_persist"] = await rollback_persist(ctx);
      return;
    }
    default: throw new Error(`unknown verb id: ${id}`);
  }
}

export async function run(input: any): Promise<Ctx> {
  const ctx = newCtx(input);
  await __execute("fetch_with_retry", ctx);
  return ctx;
}
