// Generated by NOMARK Intents resolver (target: typescript)
// Composition: flow_routing v0.4.0
// Conditional pipeline: validate, route on status, map+persist on success or terminate on failure.
import { setTimeout as sleep } from "node:timers/promises";
/** Runtime context passed between verbs — values produced by prior verbs are stored here. */
export interface Ctx {
  input: any;
  values: Record<string, any>;
  receipts: Record<string, { id: string; timestamp: string; sink: string; reversible: boolean }>;
}
function newCtx(input: any): Ctx {
  return { input, values: {}, receipts: {} };
}
async function __retry<T>(fn: () => Promise<T>, max: number, delayMs: number, backoff: "linear"|"exponential", jitter: boolean): Promise<T> {
  let lastErr: unknown;
  for (let attempt = 0; attempt < max; attempt++) {
    try { return await fn(); } catch (e) { lastErr = e; }
    const base = backoff === "exponential" ? delayMs * Math.pow(2, attempt) : delayMs * (attempt + 1);
    const wait = jitter ? base * (0.5 + Math.random()) : base;
    await sleep(wait);
  }
  throw lastErr;
}
function __receipt(sink: string, reversible = true) {
  return { id: crypto.randomUUID(), timestamp: new Date().toISOString(), sink, reversible };
}
/** Minimal predicate evaluator — opaque string per spec §3.1. Resolver chose JS. */
function __predicate(expr: string, row: any): boolean {
  // eslint-disable-next-line no-new-func
  return Boolean(new Function("row", `return (${expr});`)(row));
}
function __project<T>(expr: string, input: T): any {
  // eslint-disable-next-line no-new-func
  return new Function("input", "row", `return (${expr});`)(input, input);
}
function __reduce(expr: string, input: any[], initial: any): any {
  const m = expr.match(/^group_by\(([^)]+)\)\.(sum|count|avg|min|max)\(([^)]*)\)$/);
  if (m) {
    const [, key, op, field] = m;
    const groups = new Map<any, any[]>();
    for (const row of input) {
      const k = __project(key, row);
      if (!groups.has(k)) groups.set(k, []);
      groups.get(k)!.push(row);
    }
    const out: Record<string, any> = {};
    for (const [k, rows] of groups) {
      if (op === "count") out[String(k)] = rows.length;
      else {
        const vals = rows.map(r => __project(field, r));
        if (op === "sum") out[String(k)] = vals.reduce((a, b) => a + b, 0);
        else if (op === "avg") out[String(k)] = vals.reduce((a, b) => a + b, 0) / vals.length;
        else if (op === "min") out[String(k)] = Math.min(...vals);
        else if (op === "max") out[String(k)] = Math.max(...vals);
      }
    }
    return out;
  }
  const m2 = expr.match(/^(sum|count|avg|min|max)\(([^)]*)\)$/);
  if (m2) {
    const [, op, field] = m2;
    if (op === "count") return input.length;
    const vals = input.map(r => __project(field, r));
    if (op === "sum") return vals.reduce((a, b) => a + b, 0);
    if (op === "avg") return vals.reduce((a, b) => a + b, 0) / vals.length;
    if (op === "min") return Math.min(...vals);
    if (op === "max") return Math.max(...vals);
  }
  // generic reducer: treat expr as JS lambda "acc, row => ..."
  // eslint-disable-next-line no-new-func
  const fn = new Function("acc", "row", `return (${expr});`) as (a: any, r: any) => any;
  return input.reduce(fn, initial);
}
async function fetch_data(ctx: Ctx): Promise<any> {
  const r = await fetch("https://api.example.com/records", {}); return await r.json();
}

async function validate(ctx: Ctx): Promise<any> {
  const input = ctx.input;
  const rules: any = [{"field":"status","check":"required"}];
  // Basic schema check — host may inject Ajv via globalThis.__validator.
  const v = (globalThis as any).__validator;
  const ok = v ? v(rules)(input) : true;
  if (!ok) {
    const action = "reject";
    if (action === "reject") throw new Error("VALIDATE validate failed");
    if (action === "route") { await __execute("", ctx); return ctx.values[""]; }
    if (action === "flag") return { ...input, __flagged: true };
  }
  return input;
}

async function route_by_status(ctx: Ctx): Promise<any> {
  if (__predicate("status == \"ok\"", ctx.input)) return await __execute("map_record", ctx);
  return await __execute("abort", ctx);
}

async function map_record(ctx: Ctx): Promise<any> {
  const input = ctx.input;
  return __project("{ id: id, status: status, amount: amount }", input);
}

async function persist_data(ctx: Ctx): Promise<any> {
  const input = ctx.input;
  const { default: pg } = await import("pg");
  const client = new pg.Client({"__rawJs":"process.env.DATABASE_URL"});
  await client.connect();
  try {
    const rows: any[] = Array.isArray(input) ? input : [input];
    for (const row of rows) {
      const keys = Object.keys(row); const vals = Object.values(row);
      const placeholders = keys.map((_, i) => "$" + (i+1)).join(", ");
      const sql = `INSERT INTO records (${keys.join(",")}) VALUES (${placeholders})`;
      await client.query(sql, vals);
    }
  } finally { await client.end(); }
  const receipt = __receipt("sql:records");
  ctx.receipts["persist_data"] = receipt;
  return receipt;
}

async function abort(ctx: Ctx): Promise<never> {
  const cleanup: string[] = [];
  for (const cid of cleanup) await __execute(cid, ctx);
  throw new __TerminateError("validation rejected", "failed");
}

class __TerminateError extends Error {
  constructor(public reason: string, public status: string) { super(`__TERMINATE: ${reason}`); }
}
async function __execute(id: string, ctx: Ctx): Promise<void> {
  switch (id) {
    case "fetch_data": {
      ctx.values["fetch_data"] = await fetch_data(ctx);
      return __execute("validate", ctx);
    }
    case "validate": {
      ctx.values["validate"] = await validate(ctx);
      return __execute("route_by_status", ctx);
    }
    case "route_by_status": {
      ctx.values["route_by_status"] = await route_by_status(ctx);
      return;
    }
    case "map_record": {
      ctx.values["map_record"] = await map_record(ctx);
      return __execute("persist_data", ctx);
    }
    case "persist_data": {
      ctx.values["persist_data"] = await persist_data(ctx);
      return;
    }
    case "abort": {
      ctx.values["abort"] = await abort(ctx);
      return;
    }
    default: throw new Error(`unknown verb id: ${id}`);
  }
}

export async function run(input: any): Promise<Ctx> {
  const ctx = newCtx(input);
  try {
    await __execute("fetch_data", ctx);
  } catch (e) {
    if (!(e instanceof __TerminateError)) throw e;
  }
  return ctx;
}
