// Generated by NOMARK Intents resolver (target: rust)
// Composition: daily_fund_flow_etl v0.4.0
// Pull daily fund flow rows from an HTTP source, validate, normalize, aggregate per fund, upsert into Postgres, then notify on completion.
use std::collections::HashMap;
use std::time::Duration as StdDuration;
use anyhow::{anyhow, Result};
use serde_json::{json, Value};
use tokio::time::sleep;
#[derive(Debug, Clone)]
pub struct Receipt {
    pub id: String,
    pub timestamp: String,
    pub sink: String,
    pub reversible: bool,
}
#[derive(Debug, Default)]
pub struct Ctx {
    pub input: Value,
    pub values: HashMap<String, Value>,
    pub receipts: HashMap<String, Receipt>,
}
fn new_receipt(sink: &str, reversible: bool) -> Receipt {
    Receipt {
        id: uuid::Uuid::new_v4().to_string(),
        timestamp: chrono::Utc::now().to_rfc3339(),
        sink: sink.to_string(),
        reversible,
    }
}
async fn retry<F, Fut, T>(mut f: F, max: u32, delay_ms: u64, backoff: &str, jitter: bool) -> Result<T>
where
    F: FnMut() -> Fut,
    Fut: std::future::Future<Output = Result<T>>,
{
    let mut last: Option<anyhow::Error> = None;
    for attempt in 0..max {
        match f().await {
            Ok(v) => return Ok(v),
            Err(e) => last = Some(e),
        }
        let base = if backoff == "exponential" {
            delay_ms.saturating_mul(1u64 << attempt.min(20))
        } else {
            delay_ms.saturating_mul((attempt + 1) as u64)
        };
        let wait = if jitter {
            let r: f64 = rand::random();
            ((base as f64) * (0.5 + r)) as u64
        } else { base };
        sleep(StdDuration::from_millis(wait)).await;
    }
    Err(last.unwrap_or_else(|| anyhow!("retry exhausted with no error recorded")))
}
/// Opaque predicate evaluation. Resolver choice: evalexpr over serde_json::Value.
/// Supports comparisons, arithmetic, &&, ||, !, and dotted row.field paths.
fn predicate(expr: &str, row: &Value) -> bool {
    eval_bool(expr, row).unwrap_or(false)
}
fn eval_bool(expr: &str, row: &Value) -> Option<bool> {
    // Minimal predicate engine — supports: <lhs> <op> <rhs> where op in == != < <= > >= and literal null check.
    for op in ["==", "!=", "<=", ">=", "<", ">"] {
        if let Some(idx) = expr.find(op) {
            let lhs = expr[..idx].trim();
            let rhs = expr[idx + op.len()..].trim();
            let a = resolve_expr(lhs, row);
            let b = resolve_expr(rhs, row);
            return Some(match op {
                "==" => a == b,
                "!=" => a != b,
                "<"  => cmp(&a, &b) == Some(std::cmp::Ordering::Less),
                "<=" => matches!(cmp(&a, &b), Some(std::cmp::Ordering::Less | std::cmp::Ordering::Equal)),
                ">"  => cmp(&a, &b) == Some(std::cmp::Ordering::Greater),
                ">=" => matches!(cmp(&a, &b), Some(std::cmp::Ordering::Greater | std::cmp::Ordering::Equal)),
                _ => false,
            });
        }
    }
    // Fallback: truthiness of row.<path>
    Some(!resolve_expr(expr.trim(), row).is_null())
}
fn cmp(a: &Value, b: &Value) -> Option<std::cmp::Ordering> {
    match (a.as_f64(), b.as_f64()) {
        (Some(x), Some(y)) => x.partial_cmp(&y),
        _ => a.as_str().and_then(|x| b.as_str().map(|y| x.cmp(y))),
    }
}
fn resolve_expr(e: &str, row: &Value) -> Value {
    let e = e.trim();
    if let Ok(n) = e.parse::<f64>() { return json!(n); }
    if e.starts_with('"') && e.ends_with('"') { return json!(e.trim_matches('"')); }
    if e == "null" { return Value::Null; }
    if e == "true" { return json!(true); }
    if e == "false" { return json!(false); }
    // dotted path: row.field.subfield or input.field
    let path = if let Some(s) = e.strip_prefix("row.") { s }
               else if let Some(s) = e.strip_prefix("input.") { s }
               else { e };
    let mut cur = row;
    for seg in path.split('.') {
        cur = match cur.get(seg) { Some(v) => v, None => return Value::Null };
    }
    cur.clone()
}
fn reduce_agg(expr: &str, items: &[Value]) -> Value {
    // group_by(key).op(field)
    let re_group = regex::Regex::new(r"^group_by\(([^)]+)\)\.(sum|count|avg|min|max)\(([^)]*)\)$").unwrap();
    if let Some(caps) = re_group.captures(expr) {
        let key = caps.get(1).unwrap().as_str();
        let op  = caps.get(2).unwrap().as_str();
        let field = caps.get(3).unwrap().as_str();
        let mut groups: HashMap<String, Vec<Value>> = HashMap::new();
        for row in items {
            let k = resolve_expr(key, row);
            groups.entry(k.to_string()).or_default().push(row.clone());
        }
        let mut out = serde_json::Map::new();
        for (k, rows) in groups {
            let val = match op {
                "count" => json!(rows.len()),
                "sum"   => json!(rows.iter().filter_map(|r| resolve_expr(field, r).as_f64()).sum::<f64>()),
                "avg"   => {
                    let vs: Vec<f64> = rows.iter().filter_map(|r| resolve_expr(field, r).as_f64()).collect();
                    if vs.is_empty() { json!(0) } else { json!(vs.iter().sum::<f64>() / vs.len() as f64) }
                },
                "min"   => json!(rows.iter().filter_map(|r| resolve_expr(field, r).as_f64()).fold(f64::INFINITY, f64::min)),
                "max"   => json!(rows.iter().filter_map(|r| resolve_expr(field, r).as_f64()).fold(f64::NEG_INFINITY, f64::max)),
                _ => Value::Null,
            };
            out.insert(k, val);
        }
        return Value::Object(out);
    }
    let re_single = regex::Regex::new(r"^(sum|count|avg|min|max)\(([^)]*)\)$").unwrap();
    if let Some(caps) = re_single.captures(expr) {
        let op = caps.get(1).unwrap().as_str();
        let field = caps.get(2).unwrap().as_str();
        if op == "count" { return json!(items.len()); }
        let vals: Vec<f64> = items.iter().filter_map(|r| resolve_expr(field, r).as_f64()).collect();
        return match op {
            "sum" => json!(vals.iter().sum::<f64>()),
            "avg" => if vals.is_empty() { json!(0) } else { json!(vals.iter().sum::<f64>() / vals.len() as f64) },
            "min" => json!(vals.iter().cloned().fold(f64::INFINITY, f64::min)),
            "max" => json!(vals.iter().cloned().fold(f64::NEG_INFINITY, f64::max)),
            _ => Value::Null,
        };
    }
    Value::Null
}
async fn fetch_rows(ctx: &mut Ctx) -> Result<Value> {
    { let r = reqwest::Client::new().request(reqwest::Method::from_bytes("GET".as_bytes())?, "https://api.example.com/fund-flows/daily").send().await?.error_for_status()?; Ok(r.json::<Value>().await?) }
}

async fn validate_rows(ctx: &mut Ctx) -> Result<Value> {
    let input = ctx.input.clone();
    // Default validator is pass-through. Host may inject via a feature flag.
    let ok = true;
    if !ok {
        match "reject" {
            "reject" => anyhow::bail!("VALIDATE validate_rows failed"),
            "route" => { Box::pin(_execute("", ctx)).await?;
                         return Ok(ctx.values.get("").cloned().unwrap_or(Value::Null)); }
            _ => {}
        }
    }
    Ok(input)
}

async fn normalize_region(ctx: &mut Ctx) -> Result<Value> {
    let input = ctx.input.clone();
    Ok(resolve_expr("{ fund_id: fund_id, trade_date: trade_date, flow_usd: flow_usd, region: region }", &input))
}

async fn drop_zero(ctx: &mut Ctx) -> Result<Value> {
    let input = ctx.input.clone();
    let arr = input.as_array().cloned().unwrap_or_default();
    let kept: Vec<Value> = arr.into_iter().filter(|r| predicate("flow_usd != 0", r)).collect();
    Ok(Value::Array(kept))
}

async fn aggregate_daily(ctx: &mut Ctx) -> Result<Value> {
    let input = ctx.input.clone();
    let items = input.as_array().cloned().unwrap_or_default();
    Ok(reduce_agg("group_by(fund_id,trade_date).sum(flow_usd)", &items))
}

async fn upsert_daily(ctx: &mut Ctx) -> Result<Value> {
    let input = ctx.input.clone();
    {
        let pool = sqlx::postgres::PgPoolOptions::new().connect(&std::env::var("DATABASE_URL")?).await?;
        let rows = if input.is_array() { input.as_array().cloned().unwrap_or_default() } else { vec![input.clone()] };
        for row in rows {
            let obj = row.as_object().ok_or_else(|| anyhow!("row not an object"))?;
            let keys: Vec<&String> = obj.keys().collect();
            let placeholders: Vec<String> = (1..=keys.len()).map(|i| format!("${i}")).collect();
            let cols = keys.iter().map(|k| k.as_str()).collect::<Vec<_>>().join(", ");
            let sql = format!("INSERT INTO fund_flow_daily ({}) VALUES ({})", cols, placeholders.join(", "));
            let mut q = sqlx::query(&sql);
            for k in &keys {
                q = q.bind(obj.get(k.as_str()).cloned().unwrap_or(Value::Null));
            }
            q.execute(&pool).await?;
        }
    }
    let receipt = new_receipt("sql:fund_flow_daily", true);
    ctx.receipts.insert("upsert_daily".to_string(), receipt.clone());
    Ok(json!({ "id": receipt.id, "timestamp": receipt.timestamp, "sink": receipt.sink, "reversible": receipt.reversible }))
}

async fn notify_done(ctx: &mut Ctx) -> Result<Value> {
    let payload = ctx.values.get("notify_done").cloned().unwrap_or_else(|| ctx.input.clone());
    {
        let body = json!({ "channel": "#data-ops", "text": payload });
        reqwest::Client::new().post("").json(&body).send().await?;
    }
    Ok(Value::Null)
}

#[async_recursion::async_recursion]
async fn _execute(id: &str, ctx: &mut Ctx) -> Result<()> {
    match id {
        "fetch_rows" => {
            let r = fetch_rows(ctx).await?;
            ctx.values.insert("fetch_rows".to_string(), r);
            Box::pin(_execute("validate_rows", ctx)).await?;
            Ok(())
        }
        "validate_rows" => {
            let r = validate_rows(ctx).await?;
            ctx.values.insert("validate_rows".to_string(), r);
            Box::pin(_execute("normalize_region", ctx)).await?;
            Ok(())
        }
        "normalize_region" => {
            let r = normalize_region(ctx).await?;
            ctx.values.insert("normalize_region".to_string(), r);
            Box::pin(_execute("drop_zero", ctx)).await?;
            Ok(())
        }
        "drop_zero" => {
            let r = drop_zero(ctx).await?;
            ctx.values.insert("drop_zero".to_string(), r);
            Box::pin(_execute("aggregate_daily", ctx)).await?;
            Ok(())
        }
        "aggregate_daily" => {
            let r = aggregate_daily(ctx).await?;
            ctx.values.insert("aggregate_daily".to_string(), r);
            Box::pin(_execute("upsert_daily", ctx)).await?;
            Ok(())
        }
        "upsert_daily" => {
            let r = upsert_daily(ctx).await?;
            ctx.values.insert("upsert_daily".to_string(), r);
            Box::pin(_execute("notify_done", ctx)).await?;
            Ok(())
        }
        "notify_done" => {
            let r = notify_done(ctx).await?;
            ctx.values.insert("notify_done".to_string(), r);

            Ok(())
        }
        other => Err(anyhow!("unknown verb id: {}", other)),
    }
}

pub async fn run(input: Value) -> Result<Ctx> {
    let mut ctx = Ctx { input, ..Default::default() };
    _execute("fetch_rows", &mut ctx).await?;
    Ok(ctx)
}