<!-- Generated by NOMARK Intents resolver (target: vue) -->
<!-- Composition: admin_console v0.4.0 -->
<!-- Interactive admin console: configure thresholds, decide on approvals, explore audit log, author rules, onboard new admins. -->
<script setup lang="ts">
import { h, defineRender, type VNode } from 'vue';

export type DashboardState = {
  values: Record<string, unknown>;
  status: 'idle' | 'loading' | 'empty';
  alerts: readonly string[];
  selections: Record<string, unknown>;
  drafts: Record<string, unknown>;
};

export type DashboardDispatch = (event: { verb: string; id: string; action: string; payload: unknown }) => void;

const props = defineProps<{ state: DashboardState; dispatch: DashboardDispatch }>();

function admin_view(children: readonly (VNode | null)[]): VNode {
  return h('main', {
    'data-monitor': 'admin_view',
    'data-subject': 'admin operations',
    'data-refresh': '1s',
  }, children.filter((c): c is VNode => c !== null));
}

function tabs(children: readonly VNode[]): VNode {
  return h('div', {
    'data-arrange': 'tabs',
    'data-density': 'comfortable',
    'data-children': 'threshold_form,approval_choice,audit_search,rule_editor,admin_setup,admin_email',
  }, children);
}

function threshold_form(state: DashboardState, dispatch: DashboardDispatch): VNode {
  return h('form', { 'data-configure': 'threshold_form', 'data-prompt': 'System thresholds' }, [
    h('label', null, [
      'Alert threshold (USD)',
      h('input', {
        name: 'threshold_usd',
        type: 'number',
        value: String(state.drafts['threshold_usd'] ?? state.values['threshold_usd'] ?? ''),
        onChange: (e: Event) => dispatch({ verb: 'CONFIGURE', id: 'threshold_form', action: 'set', payload: { threshold_usd: (e.target as HTMLInputElement).value } }),
      }),
    ]),
    h('label', null, [
      'Alert channel',
      h('input', {
        name: 'alert_channel',
        type: 'text',
        value: String(state.drafts['alert_channel'] ?? state.values['alert_channel'] ?? ''),
        onChange: (e: Event) => dispatch({ verb: 'CONFIGURE', id: 'threshold_form', action: 'set', payload: { alert_channel: (e.target as HTMLInputElement).value } }),
      }),
    ]),
    h('button', { type: 'button', onClick: () => dispatch({ verb: 'CONFIGURE', id: 'threshold_form', action: 'apply', payload: state.drafts }) }, 'Apply'),
  ]);
}

function approval_choice(state: DashboardState, dispatch: DashboardDispatch): VNode {
  return h('form', { 'data-decide': 'approval_choice', 'data-prompt': 'Approve this transaction?' }, [
    h('button', {
      type: 'button',
      'data-option': 'approve',
      onClick: () => dispatch({ verb: 'DECIDE', id: 'approval_choice', action: 'select', payload: 'approve' }),
    }, 'Approve'),
    h('button', {
      type: 'button',
      'data-option': 'reject',
      onClick: () => dispatch({ verb: 'DECIDE', id: 'approval_choice', action: 'select', payload: 'reject' }),
    }, 'Reject'),
  ]);
}

function audit_search(state: DashboardState, dispatch: DashboardDispatch): VNode {
  const results = (state.values['audit_log'] as readonly { id: string; label: string }[] | undefined) ?? [];
  return h('section', { 'data-explore': 'audit_search', 'data-prompt': 'Audit log', 'data-source': 'audit_log' }, [
    h('input', {
      type: 'search',
      placeholder: 'Search events...',
      value: String(state.drafts['audit_search'] ?? ''),
      onChange: (e: Event) => dispatch({ verb: 'EXPLORE', id: 'audit_search', action: 'query', payload: (e.target as HTMLInputElement).value }),
    }),
    h('ul', { role: 'listbox' }, results.map((r) => h('li', { key: r.id, 'data-result-id': r.id }, r.label))),
  ]);
}

function rule_editor(state: DashboardState, dispatch: DashboardDispatch): VNode {
  return h('form', { 'data-author': 'rule_editor', 'data-prompt': 'Edit rule', 'data-schema': 'rules.v1', 'data-save-mode': 'manual' }, [
    h('output', { 'data-schema-ref': 'rules.v1' }, String(state.drafts['rule_editor'] ?? state.values['rule_editor'] ?? '')),
    h('textarea', {
      name: 'rule_editor',
      value: String(state.drafts['rule_editor'] ?? state.values['rule_editor'] ?? ''),
      onChange: (e: Event) => dispatch({ verb: 'AUTHOR', id: 'rule_editor', action: 'edit', payload: (e.target as HTMLTextAreaElement).value }),
    }),
    h('button', { type: 'button', onClick: () => dispatch({ verb: 'AUTHOR', id: 'rule_editor', action: 'save', payload: state.drafts['rule_editor'] }) }, 'Save'),
  ]);
}

function admin_setup(state: DashboardState, dispatch: DashboardDispatch): VNode {
  const current = String(state.selections['admin_setup'] ?? 'profile');
  return h('nav', { 'data-onboard': 'admin_setup', 'data-prompt': 'New admin setup', 'data-progress-type': 'step' }, [
    h('ol', null, [
      h('li', { 'data-step': 'profile', 'data-active': String(current === 'profile') }, 'Profile'),
      h('li', { 'data-step': 'permissions', 'data-active': String(current === 'permissions') }, 'Permissions'),
      h('li', { 'data-step': 'review', 'data-active': String(current === 'review') }, 'Review'),
    ]),
    h('button', { type: 'button', 'data-step-action': 'advance', onClick: () => dispatch({ verb: 'ONBOARD', id: 'admin_setup', action: 'advance', payload: current }) }, 'Next'),
    h('button', { type: 'button', 'data-step-action': 'skip', onClick: () => dispatch({ verb: 'ONBOARD', id: 'admin_setup', action: 'skip', payload: current }) }, 'Skip'),
  ]);
}

function admin_email(state: DashboardState, dispatch: DashboardDispatch): VNode {
  return h('label', { 'data-collect': 'admin_email', 'data-collect-type': 'text' }, [
    'Admin email',
    h('input', {
      type: 'text',
      name: 'email',
      required: true,
      value: String(state.drafts['email'] ?? ''),
      onChange: (e: Event) => dispatch({ verb: 'COLLECT', id: 'admin_email', action: 'input', payload: (e.target as HTMLInputElement).value }),
    }),
  ]);
}

defineRender(() => admin_view([
  tabs([
    threshold_form(props.state, props.dispatch),
    approval_choice(props.state, props.dispatch),
    audit_search(props.state, props.dispatch),
    rule_editor(props.state, props.dispatch),
    admin_setup(props.state, props.dispatch),
    admin_email(props.state, props.dispatch),
  ]),
]));
</script>
