<!-- Generated by NOMARK Intents resolver (target: svelte) -->
<!-- Composition: admin_console v0.4.0 -->
<!-- Interactive admin console: configure thresholds, decide on approvals, explore audit log, author rules, onboard new admins. -->
<script lang="ts" module>
  export type DashboardState = {
    values: Record<string, unknown>;
    status: 'idle' | 'loading' | 'empty';
    alerts: readonly string[];
    selections: Record<string, unknown>;
    drafts: Record<string, unknown>;
  };

  export type DashboardDispatch = (event: { verb: string; id: string; action: string; payload: unknown }) => void;
</script>

<script lang="ts">
  let { state, dispatch }: { state: DashboardState; dispatch: DashboardDispatch } = $props();
</script>

{#snippet threshold_form(state: DashboardState, dispatch: DashboardDispatch)}
  <form data-configure='threshold_form' data-prompt='System thresholds'>
    <label>
      Alert threshold (USD)
      <input
        name='threshold_usd'
        type='number'
        value={String(state.drafts['threshold_usd'] ?? state.values['threshold_usd'] ?? '')}
        onchange={(e) => dispatch({ verb: 'CONFIGURE', id: 'threshold_form', action: 'set', payload: { threshold_usd: (e.currentTarget as HTMLInputElement).value } })}
      />
    </label>
    <label>
      Alert channel
      <input
        name='alert_channel'
        type='text'
        value={String(state.drafts['alert_channel'] ?? state.values['alert_channel'] ?? '')}
        onchange={(e) => dispatch({ verb: 'CONFIGURE', id: 'threshold_form', action: 'set', payload: { alert_channel: (e.currentTarget as HTMLInputElement).value } })}
      />
    </label>
    <button type='button' onclick={() => dispatch({ verb: 'CONFIGURE', id: 'threshold_form', action: 'apply', payload: state.drafts })}>Apply</button>
  </form>
{/snippet}

{#snippet approval_choice(state: DashboardState, dispatch: DashboardDispatch)}
  <form data-decide='approval_choice' data-prompt='Approve this transaction?'>
    <button type='button' data-option='approve' onclick={() => dispatch({ verb: 'DECIDE', id: 'approval_choice', action: 'select', payload: 'approve' })}>Approve</button>
    <button type='button' data-option='reject' onclick={() => dispatch({ verb: 'DECIDE', id: 'approval_choice', action: 'select', payload: 'reject' })}>Reject</button>
  </form>
{/snippet}

{#snippet audit_search(state: DashboardState, dispatch: DashboardDispatch)}
  <section data-explore='audit_search' data-prompt='Audit log' data-source='audit_log'>
    <input
      type='search'
      placeholder='Search events...'
      value={String(state.drafts['audit_search'] ?? '')}
      onchange={(e) => dispatch({ verb: 'EXPLORE', id: 'audit_search', action: 'query', payload: (e.currentTarget as HTMLInputElement).value })}
    />
    <ul role='listbox'>
      {#each ((state.values['audit_log'] as readonly { id: string; label: string }[] | undefined) ?? []) as r (r.id)}
        <li data-result-id={r.id}>{r.label}</li>
      {/each}
    </ul>
  </section>
{/snippet}

{#snippet rule_editor(state: DashboardState, dispatch: DashboardDispatch)}
  <form data-author='rule_editor' data-prompt='Edit rule' data-schema='rules.v1' data-save-mode='manual'>
    <output data-schema-ref='rules.v1'>{String(state.drafts['rule_editor'] ?? state.values['rule_editor'] ?? '')}</output>
    <textarea
      name='rule_editor'
      value={String(state.drafts['rule_editor'] ?? state.values['rule_editor'] ?? '')}
      onchange={(e) => dispatch({ verb: 'AUTHOR', id: 'rule_editor', action: 'edit', payload: (e.currentTarget as HTMLTextAreaElement).value })}
    ></textarea>
    <button type='button' onclick={() => dispatch({ verb: 'AUTHOR', id: 'rule_editor', action: 'save', payload: state.drafts['rule_editor'] })}>Save</button>
  </form>
{/snippet}

{#snippet admin_setup(state: DashboardState, dispatch: DashboardDispatch)}
  {@const current = String(state.selections['admin_setup'] ?? 'profile')}
  <nav data-onboard='admin_setup' data-prompt='New admin setup' data-progress-type='step'>
    <ol>
      <li data-step='profile' data-active={String(current === 'profile')}>Profile</li>
      <li data-step='permissions' data-active={String(current === 'permissions')}>Permissions</li>
      <li data-step='review' data-active={String(current === 'review')}>Review</li>
    </ol>
    <button type='button' data-step-action='advance' onclick={() => dispatch({ verb: 'ONBOARD', id: 'admin_setup', action: 'advance', payload: current })}>Next</button>
    <button type='button' data-step-action='skip' onclick={() => dispatch({ verb: 'ONBOARD', id: 'admin_setup', action: 'skip', payload: current })}>Skip</button>
  </nav>
{/snippet}

{#snippet admin_email(state: DashboardState, dispatch: DashboardDispatch)}
  <label data-collect='admin_email' data-collect-type='text'>
    Admin email
    <input
      type='text'
      name='email'
      required
      value={String(state.drafts['email'] ?? '')}
      onchange={(e) => dispatch({ verb: 'COLLECT', id: 'admin_email', action: 'input', payload: (e.currentTarget as HTMLInputElement).value })}
    />
  </label>
{/snippet}

{#snippet tabs(state: DashboardState, dispatch: DashboardDispatch)}
  <div
    data-arrange='tabs'
    data-density='comfortable'
    data-children='threshold_form,approval_choice,audit_search,rule_editor,admin_setup,admin_email'
  >
    {@render threshold_form(state, dispatch)}
    {@render approval_choice(state, dispatch)}
    {@render audit_search(state, dispatch)}
    {@render rule_editor(state, dispatch)}
    {@render admin_setup(state, dispatch)}
    {@render admin_email(state, dispatch)}
  </div>
{/snippet}

{#snippet admin_view(state: DashboardState, dispatch: DashboardDispatch)}
  <main
    data-monitor='admin_view'
    data-subject='admin operations'
    data-refresh='1s'
  >
    {@render tabs(state, dispatch)}
  </main>
{/snippet}

{@render admin_view(state, dispatch)}
