"""
Generated by NOMARK Intents resolver (target: python).
Composition: archive_compaction v0.4.0
Stream legacy fund-flow rows from Postgres, enrich each with retention metadata, delete archived rows from the source table, then notify on completion.
"""
from __future__ import annotations
import asyncio
import dataclasses
import json
import os
import random
import re
import time
import uuid
from typing import Any, Callable, Dict, List, Optional
@dataclasses.dataclass
class Ctx:
    input: Any = None
    values: Dict[str, Any] = dataclasses.field(default_factory=dict)
    receipts: Dict[str, Dict[str, Any]] = dataclasses.field(default_factory=dict)
async def _retry(fn: Callable[[], Any], max_attempts: int, delay_ms: int,
                 backoff: str = "exponential", jitter: bool = False) -> Any:
    last_err: Optional[BaseException] = None
    for attempt in range(max_attempts):
        try:
            return await fn()
        except Exception as e:
            last_err = e
        base = delay_ms * (2 ** attempt) if backoff == "exponential" else delay_ms * (attempt + 1)
        wait = base * (0.5 + random.random()) if jitter else base
        await asyncio.sleep(wait / 1000.0)
    raise last_err  # type: ignore[misc]
def _receipt(sink: str, reversible: bool = True) -> Dict[str, Any]:
    return {
        "id": str(uuid.uuid4()),
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "sink": sink,
        "reversible": reversible,
    }
def _predicate(expr: str, row: Any) -> bool:
    """Opaque expression evaluator — spec §3.1. Resolver chose Python eval."""
    return bool(eval(expr, {"__builtins__": {}}, {"row": row, "r": row}))
def _project(expr: str, input: Any) -> Any:
    return eval(expr, {"__builtins__": {"len": len, "sum": sum, "min": min, "max": max}},
                {"input": input, "row": input, "r": input})
def _reduce(expr: str, items: List[Any], initial: Any) -> Any:
    m = re.match(r"^group_by\(([^)]+)\)\.(sum|count|avg|min|max)\(([^)]*)\)$", expr)
    if m:
        key_expr, op, field = m.group(1), m.group(2), m.group(3)
        groups: Dict[Any, List[Any]] = {}
        for row in items:
            k = _project(key_expr, row)
            groups.setdefault(k, []).append(row)
        out: Dict[str, Any] = {}
        for k, rows in groups.items():
            if op == "count":
                out[str(k)] = len(rows)
                continue
            vals = [_project(field, r) for r in rows]
            if op == "sum": out[str(k)] = sum(vals)
            elif op == "avg": out[str(k)] = sum(vals) / len(vals)
            elif op == "min": out[str(k)] = min(vals)
            elif op == "max": out[str(k)] = max(vals)
        return out
    m2 = re.match(r"^(sum|count|avg|min|max)\(([^)]*)\)$", expr)
    if m2:
        op, field = m2.group(1), m2.group(2)
        if op == "count": return len(items)
        vals = [_project(field, r) for r in items]
        if op == "sum": return sum(vals)
        if op == "avg": return sum(vals) / len(vals) if vals else 0
        if op == "min": return min(vals) if vals else None
        if op == "max": return max(vals) if vals else None
    # generic lambda fallback: expr must name 'acc' and 'row'
    acc = initial
    for row in items:
        acc = eval(expr, {"__builtins__": {}}, {"acc": acc, "row": row})
    return acc
async def stream_legacy(ctx: Ctx) -> List[Any]:
    # STREAM: host should adapt this to async iteration over a real cursor.
    import asyncpg
    conn = await asyncpg.connect(os.environ.get("DATABASE_URL", ""))
    try:
        rows = await conn.fetch('SELECT * FROM fund_flow_legacy')
        return [dict(r) for r in rows]
    finally:
        await conn.close()


async def enrich_retention(ctx: Ctx) -> Any:
    input = ctx.input
    extras = {"archived_at": "now()", "retention_days": 30}
    if isinstance(input, list):
        return [{**(r if isinstance(r, dict) else {"value": r}), **extras} for r in input]
    return {**(input if isinstance(input, dict) else {"value": input}), **extras}


async def purge_archived(ctx: Ctx) -> Any:
    import asyncpg
    conn = await asyncpg.connect(os.environ.get("DATABASE_URL", ""))
    try:
        await conn.execute('DELETE FROM fund_flow_legacy WHERE archived_at < now() - interval(retention_days)')
    finally:
        await conn.close()
    receipt = _receipt("sql:fund_flow_legacy", False)
    ctx.receipts["purge_archived"] = receipt
    return receipt


async def notify_done(ctx: Ctx) -> None:
    payload = ctx.values.get("notify_done", ctx.input)
    import httpx
    async with httpx.AsyncClient() as client:
        body = {"channel": "#data-ops", "text": payload if isinstance(payload, str) else json.dumps(payload)}
        await client.post("", json=body)

async def _execute(vid: str, ctx: Ctx) -> None:
    if vid == "stream_legacy":
        ctx.values["stream_legacy"] = await stream_legacy(ctx)
        await _execute("enrich_retention", ctx)
        return
    if vid == "enrich_retention":
        ctx.values["enrich_retention"] = await enrich_retention(ctx)
        await _execute("purge_archived", ctx)
        return
    if vid == "purge_archived":
        ctx.values["purge_archived"] = await purge_archived(ctx)
        await _execute("notify_done", ctx)
        return
    if vid == "notify_done":
        ctx.values["notify_done"] = await notify_done(ctx)
        return
        return
    raise ValueError(f"unknown verb id: {vid}")

async def run(input: Any = None) -> Ctx:
    ctx = Ctx(input=input)
    await _execute("stream_legacy", ctx)
    return ctx


if __name__ == "__main__":
    asyncio.run(run())
