<!-- Generated by NOMARK Intents resolver (target: vue) -->
<!-- Composition: fund_flow_dashboard v0.4.0 -->
<!-- Read-model dashboard for fund flow monitoring. -->
<script setup lang="ts">
import { h, defineRender, type VNode } from 'vue';

export type DashboardState = {
  values: Record<string, unknown>;
  status: 'idle' | 'loading' | 'empty';
  alerts: readonly string[];
};

const props = defineProps<{ state: DashboardState }>();

function outcome(children: readonly (VNode | null)[]): VNode {
  return h('main', {
    'data-monitor': 'outcome',
    'data-subject': 'fund flows',
    'data-refresh': '5m',
  }, children.filter((c): c is VNode => c !== null));
}

function layout(children: readonly VNode[]): VNode {
  return h('div', {
    'data-arrange': 'grid',
    'data-density': 'compact',
    'data-children': 'metric_aum,chart_flows',
  }, children);
}

function metric_aum(state: DashboardState): VNode {
  return h('section', { 'data-display': 'metric_aum', 'data-type': 'metric', 'data-emphasis': 'hero' }, [
    h('header', null, 'Total AUM'),
    h('strong', null, String(state.values['aum_total'] ?? '—')),
  ]);
}

function chart_flows(state: DashboardState): VNode {
  return h('section', { 'data-display': 'chart_flows', 'data-type': 'chart', 'data-emphasis': 'standard' }, [
    h('pre', null, JSON.stringify(state.values['flow_by_fund'] ?? null, null, 2)),
  ]);
}

function loading(state: DashboardState): VNode | null {
  if (state.status !== 'loading') return null;
  return h('div', { role: 'status', 'aria-live': 'polite', 'data-status': 'loading' }, 'Fetching fund flows...');
}

function anomaly_hint(state: DashboardState): VNode | null {
  if (!state.alerts.includes('anomaly_hint')) return null;
  return h('div', { role: 'alert', 'data-guide': 'anomaly_hint', 'data-priority': 'primary' }, 'Anomalous outflow detected');
}

defineRender(() => outcome([
  loading(props.state),
  anomaly_hint(props.state),
  layout([
    metric_aum(props.state),
    chart_flows(props.state),
  ]),
]));
</script>
