// Generated by NOMARK Intents resolver (target: rust)
// Composition: flow_parallel v0.4.0
// Parallel fan-out by region, merge results, await settlement, gate on human review, signal external.
use std::collections::HashMap;
use std::time::Duration as StdDuration;
use anyhow::{anyhow, Result};
use serde_json::{json, Value};
use tokio::time::sleep;
#[derive(Debug, Clone)]
pub struct Receipt {
    pub id: String,
    pub timestamp: String,
    pub sink: String,
    pub reversible: bool,
}
#[derive(Debug, Default)]
pub struct Ctx {
    pub input: Value,
    pub values: HashMap<String, Value>,
    pub receipts: HashMap<String, Receipt>,
}
fn new_receipt(sink: &str, reversible: bool) -> Receipt {
    Receipt {
        id: uuid::Uuid::new_v4().to_string(),
        timestamp: chrono::Utc::now().to_rfc3339(),
        sink: sink.to_string(),
        reversible,
    }
}
async fn retry<F, Fut, T>(mut f: F, max: u32, delay_ms: u64, backoff: &str, jitter: bool) -> Result<T>
where
    F: FnMut() -> Fut,
    Fut: std::future::Future<Output = Result<T>>,
{
    let mut last: Option<anyhow::Error> = None;
    for attempt in 0..max {
        match f().await {
            Ok(v) => return Ok(v),
            Err(e) => last = Some(e),
        }
        let base = if backoff == "exponential" {
            delay_ms.saturating_mul(1u64 << attempt.min(20))
        } else {
            delay_ms.saturating_mul((attempt + 1) as u64)
        };
        let wait = if jitter {
            let r: f64 = rand::random();
            ((base as f64) * (0.5 + r)) as u64
        } else { base };
        sleep(StdDuration::from_millis(wait)).await;
    }
    Err(last.unwrap_or_else(|| anyhow!("retry exhausted with no error recorded")))
}
/// Opaque predicate evaluation. Resolver choice: evalexpr over serde_json::Value.
/// Supports comparisons, arithmetic, &&, ||, !, and dotted row.field paths.
fn predicate(expr: &str, row: &Value) -> bool {
    eval_bool(expr, row).unwrap_or(false)
}
fn eval_bool(expr: &str, row: &Value) -> Option<bool> {
    // Minimal predicate engine — supports: <lhs> <op> <rhs> where op in == != < <= > >= and literal null check.
    for op in ["==", "!=", "<=", ">=", "<", ">"] {
        if let Some(idx) = expr.find(op) {
            let lhs = expr[..idx].trim();
            let rhs = expr[idx + op.len()..].trim();
            let a = resolve_expr(lhs, row);
            let b = resolve_expr(rhs, row);
            return Some(match op {
                "==" => a == b,
                "!=" => a != b,
                "<"  => cmp(&a, &b) == Some(std::cmp::Ordering::Less),
                "<=" => matches!(cmp(&a, &b), Some(std::cmp::Ordering::Less | std::cmp::Ordering::Equal)),
                ">"  => cmp(&a, &b) == Some(std::cmp::Ordering::Greater),
                ">=" => matches!(cmp(&a, &b), Some(std::cmp::Ordering::Greater | std::cmp::Ordering::Equal)),
                _ => false,
            });
        }
    }
    // Fallback: truthiness of row.<path>
    Some(!resolve_expr(expr.trim(), row).is_null())
}
fn cmp(a: &Value, b: &Value) -> Option<std::cmp::Ordering> {
    match (a.as_f64(), b.as_f64()) {
        (Some(x), Some(y)) => x.partial_cmp(&y),
        _ => a.as_str().and_then(|x| b.as_str().map(|y| x.cmp(y))),
    }
}
fn resolve_expr(e: &str, row: &Value) -> Value {
    let e = e.trim();
    if let Ok(n) = e.parse::<f64>() { return json!(n); }
    if e.starts_with('"') && e.ends_with('"') { return json!(e.trim_matches('"')); }
    if e == "null" { return Value::Null; }
    if e == "true" { return json!(true); }
    if e == "false" { return json!(false); }
    // dotted path: row.field.subfield or input.field
    let path = if let Some(s) = e.strip_prefix("row.") { s }
               else if let Some(s) = e.strip_prefix("input.") { s }
               else { e };
    let mut cur = row;
    for seg in path.split('.') {
        cur = match cur.get(seg) { Some(v) => v, None => return Value::Null };
    }
    cur.clone()
}
fn reduce_agg(expr: &str, items: &[Value]) -> Value {
    // group_by(key).op(field)
    let re_group = regex::Regex::new(r"^group_by\(([^)]+)\)\.(sum|count|avg|min|max)\(([^)]*)\)$").unwrap();
    if let Some(caps) = re_group.captures(expr) {
        let key = caps.get(1).unwrap().as_str();
        let op  = caps.get(2).unwrap().as_str();
        let field = caps.get(3).unwrap().as_str();
        let mut groups: HashMap<String, Vec<Value>> = HashMap::new();
        for row in items {
            let k = resolve_expr(key, row);
            groups.entry(k.to_string()).or_default().push(row.clone());
        }
        let mut out = serde_json::Map::new();
        for (k, rows) in groups {
            let val = match op {
                "count" => json!(rows.len()),
                "sum"   => json!(rows.iter().filter_map(|r| resolve_expr(field, r).as_f64()).sum::<f64>()),
                "avg"   => {
                    let vs: Vec<f64> = rows.iter().filter_map(|r| resolve_expr(field, r).as_f64()).collect();
                    if vs.is_empty() { json!(0) } else { json!(vs.iter().sum::<f64>() / vs.len() as f64) }
                },
                "min"   => json!(rows.iter().filter_map(|r| resolve_expr(field, r).as_f64()).fold(f64::INFINITY, f64::min)),
                "max"   => json!(rows.iter().filter_map(|r| resolve_expr(field, r).as_f64()).fold(f64::NEG_INFINITY, f64::max)),
                _ => Value::Null,
            };
            out.insert(k, val);
        }
        return Value::Object(out);
    }
    let re_single = regex::Regex::new(r"^(sum|count|avg|min|max)\(([^)]*)\)$").unwrap();
    if let Some(caps) = re_single.captures(expr) {
        let op = caps.get(1).unwrap().as_str();
        let field = caps.get(2).unwrap().as_str();
        if op == "count" { return json!(items.len()); }
        let vals: Vec<f64> = items.iter().filter_map(|r| resolve_expr(field, r).as_f64()).collect();
        return match op {
            "sum" => json!(vals.iter().sum::<f64>()),
            "avg" => if vals.is_empty() { json!(0) } else { json!(vals.iter().sum::<f64>() / vals.len() as f64) },
            "min" => json!(vals.iter().cloned().fold(f64::INFINITY, f64::min)),
            "max" => json!(vals.iter().cloned().fold(f64::NEG_INFINITY, f64::max)),
            _ => Value::Null,
        };
    }
    Value::Null
}
async fn fetch_orders(ctx: &mut Ctx) -> Result<Value> {
    { let r = reqwest::Client::new().request(reqwest::Method::from_bytes("GET".as_bytes())?, "https://api.example.com/orders").send().await?.error_for_status()?; Ok(r.json::<Value>().await?) }
}

async fn fan_out(ctx: &mut Ctx) -> Result<Value> {
    let targets: Vec<&str> = serde_json::from_str("[\"process_north\",\"process_south\",\"process_east\"]")?;
    let input = ctx.input.clone();
    let mut results: Vec<Value> = Vec::new();
    for t in &targets {
        let mut branch = Ctx { input: input.clone(), ..Default::default() };
        Box::pin(_execute(t, &mut branch)).await?;
        results.push(branch.values.get(*t).cloned().unwrap_or(Value::Null));
    }
    ctx.values.insert(format!("{}:branches", "fan_out"), Value::Array(results.clone()));
    Ok(Value::Array(results))
}

async fn process_north(ctx: &mut Ctx) -> Result<Value> {
    let input = ctx.input.clone();
    Ok(resolve_expr("{ id: id, region: 'north', amount: amount }", &input))
}

async fn process_south(ctx: &mut Ctx) -> Result<Value> {
    let input = ctx.input.clone();
    Ok(resolve_expr("{ id: id, region: 'south', amount: amount }", &input))
}

async fn process_east(ctx: &mut Ctx) -> Result<Value> {
    let input = ctx.input.clone();
    Ok(resolve_expr("{ id: id, region: 'east', amount: amount }", &input))
}

async fn fan_in(ctx: &mut Ctx) -> Result<Value> {
    let key = format!("{}:branches", "fan_out");
    let branches = ctx.values.get(&key).cloned().unwrap_or(Value::Array(Vec::new()));
    let arr = branches.as_array().cloned().unwrap_or_default();
    if "all" == "first" { return Ok(arr.into_iter().next().unwrap_or(Value::Null)); }
    if "all" == "majority" {
        let mut counts: std::collections::HashMap<String, i64> = std::collections::HashMap::new();
        for b in &arr { *counts.entry(b.to_string()).or_insert(0) += 1; }
        let best = counts.into_iter().max_by_key(|(_, n)| *n);
        return Ok(best.and_then(|(k, _)| serde_json::from_str(&k).ok()).unwrap_or(Value::Null));
    }
    let mut flat: Vec<Value> = Vec::new();
    for b in arr { if let Some(a) = b.as_array() { flat.extend(a.clone()); } else { flat.push(b); } }
    Ok(Value::Array(flat))
}

async fn settle_wait(ctx: &mut Ctx) -> Result<Value> {
    let _topic = "settlement.completed";
    // AWAIT: blocking on event/time/signal. Host runtime drives.
    let ev: Option<Value> = None;
    if ev.is_none() && !"".is_empty() {
        Box::pin(_execute("", ctx)).await?;
        return Ok(ctx.values.get("").cloned().unwrap_or(Value::Null));
    }
    Ok(ev.unwrap_or(Value::Null))
}

async fn human_review(ctx: &mut Ctx) -> Result<Value> {
    // GATE: human-in-the-loop. Host injects via a feature flag or trait obj.
    // Default fallback is the timeout_route (or null).
    let _prompt = "Approve this batch?";
    let decision: Option<Value> = None;
    if decision.is_none() && !"".is_empty() {
        Box::pin(_execute("", ctx)).await?;
        return Ok(ctx.values.get("").cloned().unwrap_or(Value::Null));
    }
    Ok(decision.unwrap_or(Value::Null))
}

async fn notify_external(ctx: &mut Ctx) -> Result<Value> {
    let _system = "payment-gateway";
    // SIGNAL: dispatch to external system. Host runtime drives.
    let r: Option<Value> = None;
    if r.is_none() && !"".is_empty() {
        Box::pin(_execute("", ctx)).await?;
        return Ok(ctx.values.get("").cloned().unwrap_or(Value::Null));
    }
    Ok(r.unwrap_or(Value::Null))
}

#[async_recursion::async_recursion]
async fn _execute(id: &str, ctx: &mut Ctx) -> Result<()> {
    match id {
        "fetch_orders" => {
            let r = fetch_orders(ctx).await?;
            ctx.values.insert("fetch_orders".to_string(), r);
            Box::pin(_execute("fan_out", ctx)).await?;
            Ok(())
        }
        "fan_out" => {
            let r = fan_out(ctx).await?;
            ctx.values.insert("fan_out".to_string(), r);
            Box::pin(_execute("fan_in", ctx)).await?;
            Ok(())
        }
        "process_north" => {
            let r = process_north(ctx).await?;
            ctx.values.insert("process_north".to_string(), r);

            Ok(())
        }
        "process_south" => {
            let r = process_south(ctx).await?;
            ctx.values.insert("process_south".to_string(), r);

            Ok(())
        }
        "process_east" => {
            let r = process_east(ctx).await?;
            ctx.values.insert("process_east".to_string(), r);

            Ok(())
        }
        "fan_in" => {
            let r = fan_in(ctx).await?;
            ctx.values.insert("fan_in".to_string(), r);
            Box::pin(_execute("settle_wait", ctx)).await?;
            Ok(())
        }
        "settle_wait" => {
            let r = settle_wait(ctx).await?;
            ctx.values.insert("settle_wait".to_string(), r);
            Box::pin(_execute("human_review", ctx)).await?;
            Ok(())
        }
        "human_review" => {
            let r = human_review(ctx).await?;
            ctx.values.insert("human_review".to_string(), r);
            Box::pin(_execute("notify_external", ctx)).await?;
            Ok(())
        }
        "notify_external" => {
            let r = notify_external(ctx).await?;
            ctx.values.insert("notify_external".to_string(), r);

            Ok(())
        }
        other => Err(anyhow!("unknown verb id: {}", other)),
    }
}

pub async fn run(input: Value) -> Result<Ctx> {
    let mut ctx = Ctx { input, ..Default::default() };
    match _execute("fetch_orders", &mut ctx).await {
        Ok(_) => Ok(ctx),
        Err(e) if e.to_string().starts_with("__TERMINATE:") => Ok(ctx),
        Err(e) => Err(e),
    }
}