// Generated by NOMARK Intents resolver (target: rust)
// Composition: archive_compaction v0.4.0
// Stream legacy fund-flow rows from Postgres, enrich each with retention metadata, delete archived rows from the source table, then notify on completion.
use std::collections::HashMap;
use std::time::Duration as StdDuration;
use anyhow::{anyhow, Result};
use serde_json::{json, Value};
use tokio::time::sleep;
#[derive(Debug, Clone)]
pub struct Receipt {
    pub id: String,
    pub timestamp: String,
    pub sink: String,
    pub reversible: bool,
}
#[derive(Debug, Default)]
pub struct Ctx {
    pub input: Value,
    pub values: HashMap<String, Value>,
    pub receipts: HashMap<String, Receipt>,
}
fn new_receipt(sink: &str, reversible: bool) -> Receipt {
    Receipt {
        id: uuid::Uuid::new_v4().to_string(),
        timestamp: chrono::Utc::now().to_rfc3339(),
        sink: sink.to_string(),
        reversible,
    }
}
async fn retry<F, Fut, T>(mut f: F, max: u32, delay_ms: u64, backoff: &str, jitter: bool) -> Result<T>
where
    F: FnMut() -> Fut,
    Fut: std::future::Future<Output = Result<T>>,
{
    let mut last: Option<anyhow::Error> = None;
    for attempt in 0..max {
        match f().await {
            Ok(v) => return Ok(v),
            Err(e) => last = Some(e),
        }
        let base = if backoff == "exponential" {
            delay_ms.saturating_mul(1u64 << attempt.min(20))
        } else {
            delay_ms.saturating_mul((attempt + 1) as u64)
        };
        let wait = if jitter {
            let r: f64 = rand::random();
            ((base as f64) * (0.5 + r)) as u64
        } else { base };
        sleep(StdDuration::from_millis(wait)).await;
    }
    Err(last.unwrap_or_else(|| anyhow!("retry exhausted with no error recorded")))
}
/// Opaque predicate evaluation. Resolver choice: evalexpr over serde_json::Value.
/// Supports comparisons, arithmetic, &&, ||, !, and dotted row.field paths.
fn predicate(expr: &str, row: &Value) -> bool {
    eval_bool(expr, row).unwrap_or(false)
}
fn eval_bool(expr: &str, row: &Value) -> Option<bool> {
    // Minimal predicate engine — supports: <lhs> <op> <rhs> where op in == != < <= > >= and literal null check.
    for op in ["==", "!=", "<=", ">=", "<", ">"] {
        if let Some(idx) = expr.find(op) {
            let lhs = expr[..idx].trim();
            let rhs = expr[idx + op.len()..].trim();
            let a = resolve_expr(lhs, row);
            let b = resolve_expr(rhs, row);
            return Some(match op {
                "==" => a == b,
                "!=" => a != b,
                "<"  => cmp(&a, &b) == Some(std::cmp::Ordering::Less),
                "<=" => matches!(cmp(&a, &b), Some(std::cmp::Ordering::Less | std::cmp::Ordering::Equal)),
                ">"  => cmp(&a, &b) == Some(std::cmp::Ordering::Greater),
                ">=" => matches!(cmp(&a, &b), Some(std::cmp::Ordering::Greater | std::cmp::Ordering::Equal)),
                _ => false,
            });
        }
    }
    // Fallback: truthiness of row.<path>
    Some(!resolve_expr(expr.trim(), row).is_null())
}
fn cmp(a: &Value, b: &Value) -> Option<std::cmp::Ordering> {
    match (a.as_f64(), b.as_f64()) {
        (Some(x), Some(y)) => x.partial_cmp(&y),
        _ => a.as_str().and_then(|x| b.as_str().map(|y| x.cmp(y))),
    }
}
fn resolve_expr(e: &str, row: &Value) -> Value {
    let e = e.trim();
    if let Ok(n) = e.parse::<f64>() { return json!(n); }
    if e.starts_with('"') && e.ends_with('"') { return json!(e.trim_matches('"')); }
    if e == "null" { return Value::Null; }
    if e == "true" { return json!(true); }
    if e == "false" { return json!(false); }
    // dotted path: row.field.subfield or input.field
    let path = if let Some(s) = e.strip_prefix("row.") { s }
               else if let Some(s) = e.strip_prefix("input.") { s }
               else { e };
    let mut cur = row;
    for seg in path.split('.') {
        cur = match cur.get(seg) { Some(v) => v, None => return Value::Null };
    }
    cur.clone()
}
fn reduce_agg(expr: &str, items: &[Value]) -> Value {
    // group_by(key).op(field)
    let re_group = regex::Regex::new(r"^group_by\(([^)]+)\)\.(sum|count|avg|min|max)\(([^)]*)\)$").unwrap();
    if let Some(caps) = re_group.captures(expr) {
        let key = caps.get(1).unwrap().as_str();
        let op  = caps.get(2).unwrap().as_str();
        let field = caps.get(3).unwrap().as_str();
        let mut groups: HashMap<String, Vec<Value>> = HashMap::new();
        for row in items {
            let k = resolve_expr(key, row);
            groups.entry(k.to_string()).or_default().push(row.clone());
        }
        let mut out = serde_json::Map::new();
        for (k, rows) in groups {
            let val = match op {
                "count" => json!(rows.len()),
                "sum"   => json!(rows.iter().filter_map(|r| resolve_expr(field, r).as_f64()).sum::<f64>()),
                "avg"   => {
                    let vs: Vec<f64> = rows.iter().filter_map(|r| resolve_expr(field, r).as_f64()).collect();
                    if vs.is_empty() { json!(0) } else { json!(vs.iter().sum::<f64>() / vs.len() as f64) }
                },
                "min"   => json!(rows.iter().filter_map(|r| resolve_expr(field, r).as_f64()).fold(f64::INFINITY, f64::min)),
                "max"   => json!(rows.iter().filter_map(|r| resolve_expr(field, r).as_f64()).fold(f64::NEG_INFINITY, f64::max)),
                _ => Value::Null,
            };
            out.insert(k, val);
        }
        return Value::Object(out);
    }
    let re_single = regex::Regex::new(r"^(sum|count|avg|min|max)\(([^)]*)\)$").unwrap();
    if let Some(caps) = re_single.captures(expr) {
        let op = caps.get(1).unwrap().as_str();
        let field = caps.get(2).unwrap().as_str();
        if op == "count" { return json!(items.len()); }
        let vals: Vec<f64> = items.iter().filter_map(|r| resolve_expr(field, r).as_f64()).collect();
        return match op {
            "sum" => json!(vals.iter().sum::<f64>()),
            "avg" => if vals.is_empty() { json!(0) } else { json!(vals.iter().sum::<f64>() / vals.len() as f64) },
            "min" => json!(vals.iter().cloned().fold(f64::INFINITY, f64::min)),
            "max" => json!(vals.iter().cloned().fold(f64::NEG_INFINITY, f64::max)),
            _ => Value::Null,
        };
    }
    Value::Null
}
async fn stream_legacy(ctx: &mut Ctx) -> Result<Value> {
    // STREAM: host should adapt this to async iteration over a real cursor.
    let pool = sqlx::postgres::PgPoolOptions::new().connect(&std::env::var("DATABASE_URL")?).await?;
    let rows: Vec<Value> = sqlx::query_scalar::<_, Value>("SELECT row_to_json(t) FROM fund_flow_legacy t").fetch_all(&pool).await?;
    Ok(Value::Array(rows))
}

async fn enrich_retention(ctx: &mut Ctx) -> Result<Value> {
    let input = ctx.input.clone();
    let extras: Value = serde_json::from_str("{\"archived_at\":\"now()\",\"retention_days\":30}")?;
    let merge = |row: &Value| -> Value {
        let mut m = row.as_object().cloned().unwrap_or_default();
        if let Some(o) = extras.as_object() { for (k, v) in o { m.insert(k.clone(), v.clone()); } }
        Value::Object(m)
    };
    Ok(if input.is_array() {
        Value::Array(input.as_array().unwrap().iter().map(merge).collect())
    } else {
        merge(&input)
    })
}

async fn purge_archived(ctx: &mut Ctx) -> Result<Value> {
    {
        let pool = sqlx::postgres::PgPoolOptions::new().connect(&std::env::var("DATABASE_URL")?).await?;
        sqlx::query("DELETE FROM fund_flow_legacy WHERE archived_at < now() - interval(retention_days)").execute(&pool).await?;
    }
    let receipt = new_receipt("sql:fund_flow_legacy", false);
    ctx.receipts.insert("purge_archived".to_string(), receipt.clone());
    Ok(json!({ "id": receipt.id, "timestamp": receipt.timestamp, "sink": receipt.sink, "reversible": receipt.reversible }))
}

async fn notify_done(ctx: &mut Ctx) -> Result<Value> {
    let payload = ctx.values.get("notify_done").cloned().unwrap_or_else(|| ctx.input.clone());
    {
        let body = json!({ "channel": "#data-ops", "text": payload });
        reqwest::Client::new().post("").json(&body).send().await?;
    }
    Ok(Value::Null)
}

#[async_recursion::async_recursion]
async fn _execute(id: &str, ctx: &mut Ctx) -> Result<()> {
    match id {
        "stream_legacy" => {
            let r = stream_legacy(ctx).await?;
            ctx.values.insert("stream_legacy".to_string(), r);
            Box::pin(_execute("enrich_retention", ctx)).await?;
            Ok(())
        }
        "enrich_retention" => {
            let r = enrich_retention(ctx).await?;
            ctx.values.insert("enrich_retention".to_string(), r);
            Box::pin(_execute("purge_archived", ctx)).await?;
            Ok(())
        }
        "purge_archived" => {
            let r = purge_archived(ctx).await?;
            ctx.values.insert("purge_archived".to_string(), r);
            Box::pin(_execute("notify_done", ctx)).await?;
            Ok(())
        }
        "notify_done" => {
            let r = notify_done(ctx).await?;
            ctx.values.insert("notify_done".to_string(), r);

            Ok(())
        }
        other => Err(anyhow!("unknown verb id: {}", other)),
    }
}

pub async fn run(input: Value) -> Result<Ctx> {
    let mut ctx = Ctx { input, ..Default::default() };
    _execute("stream_legacy", &mut ctx).await?;
    Ok(ctx)
}